### ISSUE TITLE
NPF Video Property Wrong Type 

### ISSUE THREAD

**Issue by highthunder** [tumblr/docs#1]
The `media` property of the video content block is shown as having a type of `string` even though the description says that it is a media object.

**Comment by highthunder** [comment]
Other discrepancies:
NPF audio content "media" is also shown with the type "string"

NPF video content metadata description references an audio track

NPF video content attribution references an audio track

![screenshot from 2018-10-22 00-05-03](https://user-images.githubusercontent.com/5083761/47277400-27868600-d58e-11e8-8aff-506e437cf015.png)

It isn't clear if "poster" properties should contain an array of media objects or just a single one.

**Comment by sndsgd** [comment]
Thanks for the report! We've addressed these issues in https://github.com/tumblr/docs/commit/045c659dce220e8f1f3e399bb34e60fa646e1172. If you come across anything else, feel free to open another issue 👍
