### ISSUE TITLE
tumblr native audio iframes come down from the API with a 150px height

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#10]
Hey! Time for my weekly npf github issue. So, when I request a tumblr audio element, it comes back from the API with an `embed_html` property:

```json
{
  "type": "audio",
  "provider": "tumblr",
  "url": null,
  "title": "Superman",
  "artist": "Goldfinger",
  "embed_html": "<iframe class=\"tumblr_audio_player tumblr_audio_player_188362327635\" src=\"https://nightpool.tumblr.com/post/188362327635/audio_player_iframe/nightpool/tumblr_pc5r12Frjn1ti5914?audio_file=https%3A%2F%2Fa.tumblr.com%2Ftumblr_pc5r12Frjn1ti5914o1.mp3\" frameborder=\"0\" allowtransparency=\"true\" scrolling=\"no\" width=\"540\" height=\"169\"></iframe>",
  "media": {
    "url": "https://a.tumblr.com/tumblr_pc5r12Frjn1ti5914o1.mp3?play_key=e6ba8f023e92bbb5aaf06052cd0c6551",
    "type": "audio/mpeg"
  },
  "poster": [
    {
      "url": "https://66.media.tumblr.com/tumblr_pc5r12Frjn1ti5914o1_1532078103_cover.jpg",
      "type": "image/jpeg",
      "width": 500,
      "height": 500
    }
  ]
}
```

this is cool! however, the iframe comes with the attributes `width="540" height="169"` and the content doesn't begin to fill that space:

![image](https://user-images.githubusercontent.com/233815/69487873-64771900-0e2f-11ea-8a57-890585a74a81.png)

Inspecting the source code, the inner content is 85px tall, and it stretches to fill the space horizontally. It seems like instead this these attributes should be `height="85px" width="100%"`, right?

**Comment by cyle** [comment]
Hey @nightpool, looks like you found a bug. Would you mind sending this along to https://www.tumblr.com/support so we can track it properly? Thanks!

**Comment by nightpool** [comment]
will do!

**Comment by cyle** [comment]
Thanks! I'll close this so we can track it there.

**Comment by nightpool** [comment]
Filed as [zendesk ticket 7613397](https://tumblr.zendesk.com/hc/requests/7613397)
