### ISSUE TITLE
Add avatar image links to the blog.theme object in NPF data

### ISSUE THREAD

**Issue by enchanted-sword** [tumblr/docs#102]
The blog.theme object in post NPF data contains several types of header image links and its original width and height, as well as the avatar shape, but not the avatar links. These can easily be fetched via the API, but for the sake of consistency it would make sense to add it to the blog.theme object, especially since it already contains the avatar shape.

**Comment by cyle** [comment]
Hello! The `avatar` field with links should be top-level in the `blog` object as a sibling of `theme`, not within the `theme` object. But I can see that we're accidentally not including that in the NPF JSON `trail` items. We can update that on our side! Thanks for pointing this out.

**Comment by cyle** [comment]
The blog `avatar` field should be available now in `trail` items that have a `blog` object, and it'll be in that object alongside `theme`.
