### ISSUE TITLE
Avatar URL not returned in /notes endpoint

### ISSUE THREAD

**Issue by suleymangezsat** [tumblr/docs#107]
Currently, when I make a request to retrieve notes, the response does not include the avatar URL for any of the notes.

I would like to know if I need to change the request to get this information or if the current API version just doesn't provide it at all.

Example request: `https://api.tumblr.com/v2/blog/{blog-identifier}/notes?id={post-id}&mode=all`
Response:
```
{
  "meta": {
    "status": 200,
    "msg": "OK"
  },
  "response": {
    "notes": [
      {
        "type": "like",
        "timestamp": 1620593131,
        "blog_name": "blog1",
        "blog_uuid": "t:ABCDEF12345",
        "blog_url": "https://blog1.tumblr.com/",
        "followed": false,
        "avatar_shape": "circle"
      },
      {
        "type": "reblog",
        "timestamp": 1620592889,
        "blog_name": "blog2",
        "blog_uuid": "t:GHIJKL56789",
        "blog_url": "https://blog2.tumblr.com/",
        "followed": false,
        "avatar_shape": "square",
        "post_id": "987654321",
        "reblog_parent_blog_name": "blog3"
      }
    ]
  }
}
```

**Comment by cyle** [comment]
The current API accidentally only includes that information for our Official Tumblr apps, but there's no reason it can't be updated to include this info for you and other third-party consumers. Just an oversight on our part! I'll see what I can do here.

**Comment by nightpool** [comment]
alternatively, you can always use the static avatar route to always get a
url for the users avatar.
https://api.tumblr.com/v2/blog/<blog_identifier>/avatar
will always redirect to the user's most recent avatar, and it works without
authentication/in an img tag, etc. I believe it takes a size parameter as
well.

**Comment by suleymangezsat** [comment]
@cyle Thank you for your response and for looking into the issue. It would be helpful to return it in note objects. I look forward to hearing about any updates.

@nightpool I would prefer to get this information from the note object without extra redirection. Also, I guess the size feature is not working. Even though I give the size 30, it returns a 64x64 image. Or am I doing something wrong?
Example request: `https://api.tumblr.com/v2/blog/${note.blog_uuid}/avatar/30`

**Comment by nightpool** [comment]
The size feature can only choose between the precomputed sizes Tumblr makes
available.

Out of curiosity—what use case do you have that makes the redirection
harder to use? Every HTTP library I'm aware of should handle the
redirection automatically without you doing any extra work.

**Comment by suleymangezsat** [comment]
I sent the size as _30_, specified as precomputed in the API documentation.

Regarding redirection, while it's true that most HTTP libraries handle it automatically, I wanted to avoid unnecessary requests and potential performance issues. Additionally, it would be more convenient to have the avatar URL directly available in the note object, especially when dealing with a large number of notes.

**Comment by cyle** [comment]
The `avatar_url` object is now included in the response, and it has two fields: `64` and `128`, which are the two avatar size classes. Each value is that avatar size's URL.
