### ISSUE TITLE
Unique user identifier

### ISSUE THREAD

**Issue by kit0kat** [tumblr/docs#108]
Hello,

I noticed that the `/user/info` endpoint does not return a unique user id (only the `name`). Since Tumblr users can edit their username at any time, it is not possible to uniquely identify a user after a name change. This becomes a problem, e.g. if you want to use Tumblr as a single sign-on method.

I would appreciate a unique and unchangeable user id to be returned in addition to the username.

Kind regards

**Comment by cyle** [comment]
Hello @kit0kat ! The best way to get a unique identifier like you want, for a specific "user", is to use their primary blog's `uuid`. That will always be the same, regardless of their primary blog's `name` or `url`.

**Comment by kit0kat** [comment]
Hey @cyle 

Thank you very much for you quick reply!

The primary blog uuid should indeed be fine for my use case. Thx for the advice.
