### ISSUE TITLE
Unable to retrieve information from certain users

### ISSUE THREAD

**Issue by jessrheb** [tumblr/docs#109]
I am working on a little project and during the testing phase I got 404 responses when trying to retrieve information from certain random users. At first I thought it could be because these users had dashboard-only blogs (it was the only pattern I was able to notice), but then I came across other dashboard-only blogs and I was able to retrieve information from them just fine. 

To my surprise, I can't access my own main blog's information either, and it is a dashboard-only blog. It's instant 404 for it and for the others that thwarted my tests, doesn't matter what I'm trying to retrieve (blog or post info).

Is this expected or is there something I'm missing? In case anyone wants to try, I found that **@melnchly** yields 404, but **@w4ntd** works as expected, and both are dashboard-only blogs. Thank you very much in advance, if anyone can tell me why this happens.

**Comment by marcustyphoon** [comment]
I assume this is due to the "Hide [blogname] from people without an account" option near the bottom of the blog settings! (https://www.tumblr.com/melnchly does not work in an incognito window/while logged out.) Are you using authenticated API requests? If not, it makes sense that you wouldn't be able to access these blogs.

**Comment by jessrheb** [comment]
Yes, that makes sense! And it was my first suspicion since my blog really was hidden from non-Tumblr users. Ever since I posted this too I experimented with turning it on and off, just to confirm. I was just puzzled because even without authenticated API requests I was able to access some hidden blogs while others not, so the whole thing felt a bit fickle to me. Thanks for the confirmation, I appreciate it!

**Comment by marcustyphoon** [comment]
Yep, there's a difference between a dashboard-only blog (unchecked "enable custom theme" option) and a hidden-from-logged-out-users blog (checked "hide from people without a count" option)! The second one forces the first one to be true, but not vice versa.

**Comment by cyle** [comment]
Hello y'all, I'm glad you were able to figure this out! To confirm, @marcustyphoon 's answer is correct.
