### ISSUE TITLE
broken_blog_name with no broken_blog object

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#11]
The current NPF docs say that the reblog trail has the `broken_blog` property, with a nested `name` and `avatar`. However, the example includes a `broken_blog_name` property that's mentioned nowhere else in the document. Recently (not sure when), broken reblog trails have stopped including `broken_blog` entirely. Has the broken_blog property been deprecated and removed?

**Comment by cyle** [comment]
Ah, thanks for pointing this out @nightpool -- we changed the backend implementation without updating the docs fully. I'll clean this up.

**Comment by cyle** [comment]
Should be cleaned up now in this commit: https://github.com/tumblr/docs/commit/daab9e5d40aa12348115db1846f855c8c49919cc

Thanks for calling this out!
