### ISSUE TITLE
API console seems to not work

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#112]
I registered a new application under "my applications". If I press "Explore API" it opens a new page asking for the consumer key and secret. I copy those from the previous page (app page), press authenticate and I get back to the same page, no error whatsoever but also no API access. I tried it in both Firefox and Chrome, also private/incognito windows. In devtools I see a bunch of 200 OK only (and a 302 from a certain scorecardsearch)

PS: the consumer key+secret seem to work in Postman, I get a temporary oauth key/secret pair from /request_token...

**Comment by sanmai** [comment]
Do you have HTTP referrers disabled by any chance? The API console relies on them to do its magic.

**Comment by MinmoTech** [comment]
I seem to be having the same issue.

I have tried every possible combination of referer settings in firefox

**Comment by sorin-costea** [comment]
I don't even know what those referrers are :) so definitely not disabled (neither in Chrome)

**Comment by steve-dev-55** [comment]
I have the same issue with this page"?

**Comment by sanmai** [comment]
Just so you all know, we are aware of this issue and planning to fix it.

In meantime try setting `Default callback URL` to `https://api.tumblr.com/console/calls/user/info` to get console working.

**Comment by sorin-costea** [comment]
Yup with that callback the console works again - in the meantime :)

**Comment by sanmai** [comment]
Sounds like we fixed the problem. Can I get y'all to confirm the fix?

**Comment by mohanjeetsingh** [comment]
Facing same issue.
