### ISSUE TITLE
Can't create access tokens

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#113]
I'm trying to get the Oauth1 access tokens, and using Postman so I can see what's going on. So I created a new app in my account, and I have its consumer key and secret.
1. I send the authenticated GET all fine, I get the temporary token/secret. Good
2. The unauthenticated GET to the authorize endpoint wants to redirect me to the tumblr login page. And the redirect has anyway no oauth_verifier parameter, only the oauth_token. So the flow stops here.

I don' understand what I'm doing wrong here... I have a localhost address configured as callback URL, so I don't understand the redirect to Tumblr login, or the missing verifier parameter.

**Comment by sorin-costea** [comment]
@cyle  I do have a support ticket indeed but I kinda gave up on it.

But just to clarify: is this a documentation issue, or a technical issue? Because if it's the former you can just hint me and I'll pick it from there - otherwise I assume a fix will need quite a while.

**Comment by cyle** [comment]
I'm guessing this is the same technical issue on our side as https://github.com/tumblr/docs/issues/112

cc @sanmai

**Comment by sanmai** [comment]
Are you logging in with Google/Apple by any chance?

**Comment by sorin-costea** [comment]
No, just regular email login.

**Comment by sorin-costea** [comment]
As far as I can tell, it works now. So as I'm the one who opened this, I'll close it. Thank you!
