### ISSUE TITLE
Tumblr SSO does not work when "Continue with Google" is used

### ISSUE THREAD

**Issue by kit0kat** [tumblr/docs#117]
Hi,

I have integrated Tumblr SSO into my web application. Everything works fine when the user uses their email and password to sign in to Tumblr.

However, when the user chooses "Continue with Google" in the authentication flow and the user successfully signs in to Google, they are redirected to my web application with the following parameters:

error=invalid_request
error_description=Invalid or missing response type

This happens every time the user authenticates through Google.

Best regards.

**Comment by sanmai** [comment]
Hello, just to confirm: are you using OAuth 1 or OAuth 2?

**Comment by kit0kat** [comment]
> Hello, just to confirm: are you using OAuth 1 or OAuth 2?

Hi, I'm using OAuth 2

**Comment by sanmai** [comment]
I could reproduce. 

I've filed a bug ticket for this internally, hopefully we can get an answer/fix for this out soon.

**Comment by bennworks** [comment]
Hi @sanmai , this issue is also a problem with 'Continue with Apple' when using oAuth2.  BTW, oAuth1 is working normally with Google and Apple.

**Comment by sanmai** [comment]
Thanks for the wait, it is now fixed.
