### ISSUE TITLE
Expose theme properties to third-party clients

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#12]
Right now, the in-dash theme properties for a blog are not available to third-party clients. It would be really useful for rendering and customization purposes if those were available. For example, an app that referenced tumblr users could use the theme properties as an accent color for representing the user, like so:

![Untitled drawing](https://user-images.githubusercontent.com/233815/70767245-7f51f480-1d2e-11ea-9e2e-4fae1b8340c1.png)

Here are the theme properties i'm referring to:

```json
"theme": {
  "header_full_width": 1280,
  "header_full_height": 875,
  "header_focus_width": 1149,
  "header_focus_height": 646,
  "avatar_shape": "square",
  "background_color": "#523960",
  "body_font": "Helvetica Neue",
  "header_bounds": "114,1214,760,65",
  "header_image": "https://static.tumblr.com/207557b65e8e5f2b678155a3ee16c5d9/zctqgvy/U3Eo7fy4b/tumblr_static_8g3m0bj4cv8kkkwks8w0okw04.jpg",
  "header_image_focused": "https://static.tumblr.com/207557b65e8e5f2b678155a3ee16c5d9/zctqgvy/tO0pnt0yl/tumblr_static_tumblr_static_8g3m0bj4cv8kkkwks8w0okw04_focused_v3.jpg",
  "header_image_scaled": "https://assets.tumblr.com/images/default_header/optica_pattern_10_focused_v3.png?_v=eafbfb1726b334d86841955ae7b9221c",
  "header_stretch": true,
  "link_color": "#f8f5d1",
  "show_avatar": true,
  "show_description": true,
  "show_header_image": true,
  "show_title": true,
  "title_color": "#935864",
  "title_font": "Square Serif",
  "title_font_weight": "bold"
},
```

(also, my `header_image_scaled` probably shouldn't be the default header image when I have a custom header image set? that seems bad lol)

**Comment by cyle** [comment]
Hey @nightpool, I'll see what I can do. Generally this isn't the best venue for requesting new things from the API (you should contact Tumblr Support for feature requests), but I think this `theme` object was meant to be available to third parties, so it may be a bug that it's not. Furthermore, if it is supposed to be available, we definitely need some docs for it. The point about `header_image_scaled` you mentioned has a reason behind it that would be explained with docs. 😄

**Comment by cyle** [comment]
@nightpool also, what endpoint(s) are you hitting from which you'd expect to see `theme` in the `blog` objects? Even if the answer is "all of them", some examples would be useful.

**Comment by nightpool** [comment]
in this case, the only endpoint I care about is blog/{identifier}/info,
although I can imagine other people might have different usecases

**Comment by cyle** [comment]
Blog `theme` and `avatar` are now exposed to third party API consumers, outlined in this doc update: https://github.com/tumblr/docs/commit/93298da1ca5bb9875fa925861aa3a6c582a8b74b

Feel free to open new issues if you need any help with these!

**Comment by nightpool** [comment]
Thank you so much!
