### ISSUE TITLE
Tumblr seems to have no API for blog pages (pages added during theme editing)

### ISSUE THREAD

**Issue by gzombiejun** [tumblr/docs#120]
It appears that Tumblr does not provide an API endpoint for the blog pages that are added through theme editing. Users are able to add custom pages to their blogs through the theme editor, but these pages are not accessible via the existing Tumblr API.The API should offer endpoints that allow for the retrieval, creation, modification, and deletion of these pages.

**Comment by cyle** [comment]
Hello! I agree, we should! Unfortunately I don't think this is going to happen anytime soon. We don't support these pages in any of our API-driven frontends (the web, iOS, and Android apps). If they ever do get built, we'll make them publicly accessible here.

In the meantime, the best place to make feature requests like this is in the Feedback category of the Tumblr Support form: https://www.tumblr.com/support
