### ISSUE TITLE
How to get the original poster of a reblogged post?

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#123]
I get the post by ID with /posts but regardless of npf=true or not, I only receive the parent_post_url and the trail. Maybe it's my misunderstanding, shouldn't the source* fields show the original poster? Because otherwise I have to go through all the trail, doable but not sure why.

Also, how long is the returned trail? If a post is very successful, will the trail return the whole zillion reblog notes? Or only 10 and no way to fetch the rest? Because I can't find anything documented about this... I see in json a field is_root_item but if the array is bigger than 10 I guess it will never be reached.

**Comment by marcustyphoon** [comment]
Do your query with `reblog_info=true` for more info! That'll give you `reblogged_root_url`, `reblogged_root_id`, etc.

> shouldn't the source* fields show the original poster?

"source" in Tumblr internals parlance refers to the optional ability for the original poster to attach a link, i.e. this:

![image](https://github.com/tumblr/docs/assets/8336245/7b647dd0-8226-4565-b14e-518bf399c19d)

> Also, how long is the returned trail?

"trail" in Tumblr internals parlance refers to the body of the post containing content added by previous posters, so it'll be as long as the post appears on the dashboard. (So if everyone who reblogs a post adds some text in their reblog, it'll be really long—insert joke that starts with "kung pow" here—while if everyone reblogs without content it won't.) There's no "here's the whole sequence of reblogs that has led to this post being here" in the public API, I believe. (The reblog graphs on the site show that info, of course.)

**Comment by sorin-costea** [comment]
Thank you that's exactly what I needed!
