### ISSUE TITLE
HTTP 400 from Legacy Post Endpoint

### ISSUE THREAD

**Issue by Yay295** [tumblr/docs#132]
I'm trying to make a post using the legacy post endpoint, as I have done every day for [more than ten years](https://yay295.tumblr.com/archive), but I am getting an error.

Post Data:

```json
{
    "type": "text",
    "state": "published",
    "tags": "MLP, MLP:FiM, My Little Pony, Fanart",
    "format": "html",
    "body": "<p hidden>June 18, 2024 - 9 Images</p>[[MORE]]\n{more html}"
}
```

Response:

```json
{
    "meta": {
        "status": 400,
        "msg": "Bad Request"
    },
    "response": {
        "errors": [
            "Unknown state - published",
            {
                "code": 8001,
                "message": "Post cannot be empty."
            }
        ]
    }
}
```

The error response does not appear to be formatted correctly, and [error code 8001 is for NPF data](https://github.com/tumblr/docs/blob/master/api.md#errors-and-error-subcodes), which I am not using.

**Comment by bmbln** [comment]
Same issue for me, It has worked for years with the legacy post endpoint, and today "Unknown state - queue" error message

**Comment by cyle** [comment]
Sorry about that, but this should be fixed now!
