### ISSUE TITLE
weird trail format, there's a bug in there somewhere

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#133]
When I look with an API call at this post: https://churmandurr.tumblr.com/post/755755819017076736/lol-my-large-and-handsome-pig-didnt-find-anything
I get this trail:

`  
"trail": [
    {
      "blog": {
        "name": "",
        "active": false,
        "theme": [],
        "share_likes": false,
        "share_following": false,
        "can_be_followed": false
      },
      "post": {
        "id": "626287663125807105="
      },
      "content_raw": "<p>Lol my large and handsome pig didn’t find Anything of interest in your yard</p>",
      "content": "<p>Lol my large and handsome pig didn&rsquo;t find Anything of interest in your yard</p>",
      "is_root_item": true
    }
  ],
`

I wouldn't really care that the blog entry looks broken, but the ID ending with a = crashes my code which thinks (as documented) that IDs should be longs...

**Comment by marcustyphoon** [comment]
Can confirm! Looks like the `npf=true` format has more reasonable handling of broken blog items than the `npf=false` format.

**Comment by cyle** [comment]
That post looks very broken, I'm not even sure how it was created. I'll file a ticket for this though, because indeed that `=` in the post ID is incorrect / shouldn't be possible.

**Comment by sorin-costea** [comment]
PS: seems to be happening more than once, here's another one: https://strangeskeletonboy.tumblr.com/post/756369773303103488
