### ISSUE TITLE
/tagged endpoint returning incomplete results

### ISSUE THREAD

**Issue by SarenDev** [tumblr/docs#136]
When using the `/tagged` endpoint via a REST library, I noticed that the returned posts often don't match what can be seen on the site, with multiple posts missing from the result.

For example, querying the "#tears of the kingdom" tag using a future timestamp (at the time of writing) of `1724284800` returns the first post with a date of `1724200405`, even though the latest post shown on the site is dated around `1724238000`. Also, the following post returned is dated `1724185223`, while the next post on the site is dated around `1724198340`, with seven posts in between missing from the API response. The exact request used is `/v2/tagged?api_key=REDACTED&tag=tears%20of%20the%20kingdom&before=1724284800`.

While trying to diagnose the issue, I encountered several mentions of `feature_type=everything` on the Tumblr API Discussion Google Group, but this query parameter appears non-functional.

Are there query parameters I'm missing, or is the API intentionally providing partial results?

**Comment by SarenDev** [comment]
Is there an alternative API or endpoint that can achieve a similar behavior, or are there plans to roll out an update for this endpoint?

**Comment by cyle** [comment]
There's an alternative API endpoint we use for fetching posts across Tumblr that are using a specific tag or set of tags, but it's not documented publicly yet, unfortunately. However, even if we did document it that endpoint we use for our official apps has even more filtering logic applied than this legacy `GET /v2/tagged` endpoint. 

We don't have an API endpoint that lists literally all posts across Tumblr that are using a specific tag with no filtering, if that's what you're after.

**Comment by SarenDev** [comment]
Got it, thanks! Extra filtering on a search endpoint would be pretty handy, so I'll look forward to a refactor.
