### ISSUE TITLE
Assistance Needed: 403 Forbidden Error While Reblogging Queue Posts

### ISSUE THREAD

**Issue by enginkantemir** [tumblr/docs#140]
<p>I am currently developing a script to automatically reblog posts from my queue using the Tumblr API. However, I am consistently receiving a "403 Forbidden" error while attempting to execute the reblog operation. I have ensured that all the API credentials (consumer key, consumer secret, OAuth token, and OAuth token secret) are correct and active. Despite this, the issue persists.</p>

<p>I have attached the script below for your reference:</p>

<pre>
<code>
const tumblr = require('tumblr.js');
require('dotenv').config();

const TUMBLR_CONSUMER_KEY = 'xxx';
const TUMBLR_CONSUMER_SECRET = 'xxx';
const TUMBLR_OAUTH_TOKEN = 'xxx';
const TUMBLR_OAUTH_TOKEN_SECRET = 'xxx';

const client = tumblr.createClient({
  consumer_key: TUMBLR_CONSUMER_KEY,
  consumer_secret: TUMBLR_CONSUMER_SECRET,
  token: TUMBLR_OAUTH_TOKEN,
  token_secret: TUMBLR_OAUTH_TOKEN_SECRET
});

async function reblogFirstQueuePost() {
  try {
    const response = await client.blogQueue(my-blog-name.tumblr.com', { limit: 1 });

    if (response.posts && response.posts.length > 0) {
      const post = response.posts[0];

      await client.reblogPost('25-to-life.tumblr.com', {
        id: post.id,
        reblog_key: post.reblog_key,
        comment: "Automatically reblogged from queue"
      });

      console.log(`Reblogged post ${post.id} successfully.`);
    } else {
      console.log('No posts in the queue to reblog.');
    }
  } catch (error) {
    if (error.statusCode === 403) {
      console.error('Error: Forbidden. Please check your API keys and permissions.');
    } else {
      console.error('Error during reblog operation:', error);
    }
  }
}

reblogFirstQueuePost();
</code>
</pre>

<p>The error message I receive is:</p>

<pre>
<code>
Error during reblog operation: Error: API error: 403 Forbidden
at IncomingMessage. (C:\test\node_modules\tumblr.js\lib\tumblr.js:339:13)
at IncomingMessage.emit (node:events:530:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
</code>
</pre>

<p>I have verified the following:</p>

<ul>
  <li>All API credentials are correct and have the necessary permissions.</li>
  <li>The blog identifier used in the script is correct (<strong>my-blog-name.tumblr.com</strong>).</li>
  <li>The OAuth credentials are properly set up and linked to the blog.</li>
</ul>

<p>Could you please help me understand why I might be receiving this error and how to resolve it?</p>

<p>Thank you very much for your assistance.</p>

**Comment by marcustyphoon** [comment]
You can't reblog a queued post, right? If the post is in the queue it doesn't exist yet. Are you trying to immediately post the queued post, or reblog the source of the post (if it's a reblog, which it might not be)? Those should be doable.

**Comment by enginkantemir** [comment]
> You can't reblog a queued post, right? If the post is in the queue it doesn't exist yet. Are you trying to immediately post the queued post, or reblog the source of the post (if it's a reblog, which it might not be)? Those should be doable.

I added a post from the Dashboard to the queue, and I want to share that post. Which method should I use for this? Reblogging is the correct method, right?

**Comment by marcustyphoon** [comment]
For clarification: let's say I post "everybody show me some cats," a bunch of people reblog it with cat pictures, and then you queue a reblog of it with a picture of your cat. When that version of the post (with your cat) is in your queue, not posted yet, it doesn't exist publicly, so you can't reblog it from yourself. That's what `post.id` is referring to here: the post that will exist eventually.

You definitely could, however, go find the post that you reblogged in order to put it in the queue (using `reblogged_from_id`, `reblogged_from_name`, `reblogged_from_url`, etc), fetch that, and reblog that. Or you could go find the source post that I made (using `reblogged_root_id`, `reblogged_root_name`, etc), fetch it, and reblog that. Depends exactly what you're trying to do!

I'm assuming the posts you're talking about here were queued without adding any content, in which case it's less obvious why this doesn't work. But yeah, even when you don't add anything, the act of queueing a reblog gives the resulting not-yet-a-post a new ID.

**Comment by enginkantemir** [comment]
> For clarification: let's say I post "everybody show me some cats," a bunch of people reblog it with cat pictures, and then you queue a reblog of it with a picture of your cat. When that version of the post (with your cat) is in your queue, not posted yet, it doesn't exist publicly, so you can't reblog it from yourself. That's what `post.id` is referring to here: the post that will exist eventually.
> 
> You definitely could, however, go find the post that you reblogged in order to put it in the queue (using `reblogged_from_id`, `reblogged_from_name`, `reblogged_from_url`, etc), fetch that, and reblog that. Or you could go find the source post that I made (using `reblogged_root_id`, `reblogged_root_name`, etc), fetch it, and reblog that. Depends exactly what you're trying to do!
> 
> I'm assuming the posts you're talking about here were queued without adding any content, in which case it's less obvious why this doesn't work. But yeah, even when you don't add anything, the act of queueing a reblog gives the resulting not-yet-a-post a new ID.


<p>I revised my code as follows and it worked without any issues. ✅</p>

<pre>
<code>
const tumblr = require('tumblr.js');
require('dotenv').config();

const {
    TUMBLR_CONSUMER_KEY,
    TUMBLR_CONSUMER_SECRET
} = process.env;

const oauthToken = 'xxx';
const oauthTokenSecret = 'xxx';

const client = tumblr.createClient({
    consumer_key: TUMBLR_CONSUMER_KEY,
    consumer_secret: TUMBLR_CONSUMER_SECRET,
    token: oauthToken,
    token_secret: oauthTokenSecret
});

async function publishFirstQueuedPost() {
    try {
        const response = await client.blogQueue('my-blog-name', { limit: 1 });

        if (response.posts && response.posts.length > 0) {
            const post = response.posts[0];
            await client.editPost('my-blog-name', post.id, {
                state: 'published',
                content: []
            });
            console.log(`Post published successfully: ${post.id}`);
        } else {
            console.log('No posts found in the queue.');
        }
    } catch (error) {
        console.error('Error during publishing post:', error);
    }
}

publishFirstQueuedPost();
</code>
</pre>

**Comment by cyle** [comment]
I'm glad you folks figured it out! Indeed, you cannot reblog a post while it's still in a "queued" / "scheduled" state, it needs to be in a "published" state before it can be reblogged. (You can't reblog a post in "draft" state either.)
