### ISSUE TITLE
Feature request for cssMap

### ISSUE THREAD

**Issue by nobodysuspectsthebutterfly** [tumblr/docs#15]
Don't know if it's possible, but could there be a class name in the map that distinguishes when a reblog post has new content by the person posting it? There was a previous class for ".contributed-content", and I can't find anything that looks similar in the cssMap? If I'm overlooking something basic, just let me know.

**Comment by cyle** [comment]
Hello @nobodysuspectsthebutterfly ! Thanks for sending this in. It does look like this capability isn't present right now in the CSS map. Just wanted to reply that we saw this and we're investigating a potential solution. I'll reply again with the result of that. 👌

**Comment by robhdawson** [comment]
Hi @nobodysuspectsthebutterfly - you should see a fix for this in now. Rather than add a classname, though, we've added a data attribute - `data-is-contributed-content`. Hopefully that solves your issue.

**Comment by nobodysuspectsthebutterfly** [comment]
Awesome! Much appreciated.
