### ISSUE TITLE
Strange "colors" object on some image blocks

### ISSUE THREAD

**Issue by highthunder** [tumblr/docs#17]
Some Image blocks have a `colors` object that does not match the "c[0-9]*" format. Ex.
```json
"colors": {
    "04162a": 1352,
    "020f1d": 975,
    "7e4621": 850,
    "9a5229": 599,
    "4b2515": 499
}
```

From my quick tests, it appears to only happen rarely on some NSFW posts.

I have only started to see this within the past week.

Is this a bug in the API? 
A new format of the `colors` object that is just starting to roll out?

**Comment by cyle** [comment]
Hello! Looks like this is a bug, we'll fix it up. Thanks for pointing it out!

**Comment by cyle** [comment]
This should be fixed now, thanks again for pointing it out. 👌
