### ISSUE TITLE
Paginate through a post's notes?

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#19]
When retrieving a post, even if I specify "notes_info" I receive (understandably) only the first 20 notes. There's no way I can get the further notes. I somehow remember somewhere an API path to retrieve them but I can't find it again and it's definitely not documented here... so how do I retrieve all the notes?

Also, the new post API doesn't specify any "notes_info" (or "reblog_info" for that matter) does it mean retrieving notes is not supported anymore?

**Comment by cyle** [comment]
Yeah, the `notes_info` param is only meant to provide supplemental information, not actually a way to paginate through notes on a post. We have an alternate endpoint for that, which is actually available for third party API consumers to use, we've just neglected to document it. I'll see what I can do here.

**Comment by cyle** [comment]
Updated the docs with the notes-per-post-fetching endpoint: https://github.com/tumblr/docs/blob/master/api.md#notes---get-notes-for-a-specific-post
