### ISSUE TITLE
followed_by could use an example

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#20]
Because it wasn't very obvious (to me) that a correct request has to be:
```
https://api.tumblr.com/v2/blog/{blog-identifier}/followed_by?query={checked-blog-identifier}
```

**Comment by cyle** [comment]
Sure, we can add an example there. The pattern we follow is listing the required query parameters below the endpoint definition itself, in this case `query` is listed there as a required param: https://github.com/tumblr/docs/blob/master/api.md#request-parameters-5

**Comment by cyle** [comment]
Updated with an example. 👍
