### ISSUE TITLE
Display posts by post date instead of post id

### ISSUE THREAD

**Issue by andilanuza** [tumblr/docs#22]
Hello, I’m not sure if this is the right place to ask this question!

I’m using Tumblr as sort of a timeline archive so I insert newer posts in between old posts and backdate them. The backdating works on the main blog’s page (the post automatically sorts itself accdg to the post date) but I’d like my posts within my blog’s tagged pages to appear chronologically as well. The `/chrono` url should work that way (i.e `/tagged/2017/chrono`), except it sorts my posts according to _post id and not by post date_. 

My coding skills are limited, but I’d like to know if delving into the Tumblr API would allow me to retrieve published posts within a date range (i.e posts made within a specific year) and possibly sort them so it displays chronologically (by post date and not by post id), with the oldest post on top? I plan on adding a custom page still within Tumblr to display the posts (i.e `/2017`). 

Would anyone know if this is possible, or is there a better fix for this issue? 😕

**Comment by cyle** [comment]
Hello! You can kind of get what you want via the API, but you'll need to do some work in your application to do exactly what you want. You can use the [retrieve published posts](https://github.com/tumblr/docs/blob/master/api.md#posts--retrieve-published-posts) API endpoint to get posts from your blog, and you can specify a unix timestamp in the `before` parameter in that request. This should give you the 20 posts (by default) published before that time, which should leverage the publish time you used when backdating your posts. You can keep making these requests, taking the last post's published timestamp, and work backwards through the time period you want. Does that make sense?

**Comment by andilanuza** [comment]
Hi Cyle! Thanks for being generous with your time to explain it to me. Yes, the steps you listed down make sense. I was reading through the API docs and I was wondering if I was headed in the right direction. Thanks for the clarification! 😄

I hope you don't mind me asking, I’m genuinely curious—if it’s possible to display posts by **post date** instead of the **post id** (or the sequence the posts were made) on the main blog and also now on the Tumblr dashboard with the most recent update, what makes it necessary for the tagged pages’ posts to be displayed differently? 

The posts I’ve backdated only appear after a certain number of posts, not by post date but only on the _tagged pages_ of my blog (i.e. **March 8 and 29** posts appear in between two **May 16** posts within the my `/tagged/2019/chrono` page). I’ve encountered it multiple times so I’m not sure if it’s a bug or just something by default. 

Would it be a weird idea to have the posts on the blog’s tagged pages be displayed by post date by default too, especially with the `/chrono` url which ideally should [display posts chronologically](https://tumblr.zendesk.com/hc/en-us/articles/226256868-Organizing-with-tags)?

**Comment by cyle** [comment]
> I hope you don't mind me asking, I’m genuinely curious—if it’s possible to display posts by post date instead of the post id (or the sequence the posts were made) on the main blog and also now on the Tumblr dashboard with the most recent update, what makes it necessary for the tagged pages’ posts to be displayed differently?

Totally valid question, not a weird idea at all, to me. 

Currently, the way the tagged page works on individual blogs unfortunately has to be post ID based because of the way it was built many years ago. The way it works under the hood is we first query your uses of that tag, which is in one database table, which does _not_ contain the posts' publish date or other post information, only the tag-to-post-ID association. Once we have a chunk of those post IDs, we fetch the associated posts themselves, and display them to you. 

The `/chrono` option references that first step of loading the list of tag-to-post-IDs. It's an unfortunate consequence of this underlying design that it covers the _most common case_ of post IDs being descending in order the same way time is, but does not cover the case of backdated posts, which don't follow that pattern. We'd need to redesign the underlying architecture to afford for that.

So the current best way of going about a tagged page that obeys the potentially-backdated publish time is to leverage the API to build a feed kind of like what you're talking about.

**Comment by andilanuza** [comment]
Ooooh, okay yes, I think I understand how the tagged pages currently work better now. Thank you for taking the time to acknowledge my question and explain how these work behind the scenes! I don’t think Tumblr was really designed for backdating posts and viewing them under tagged pages so I understand this particular limitation with the way I’m trying to use it.

I’ve been trying to look for an explanation as to why the posts were behaving that way but I haven’t had much luck until now—so thank you! I really appreciate it. I just wanted to know if there was something I can figure out and learn to do from my end because I really want to keep using Tumblr for my blog. I’ve only recently found time to skim through the API documentation and I’m glad to know there’s still a way for me to execute what I have in mind as you’ve previously mentioned. 

Thanks again for taking the time to address my lengthy query, Cyle! 🙏

**Comment by cyle** [comment]
No worries! Happy to help. I'll close this issue but feel free to reopen or create a new issue if you run into anything else you need help with with the API.
