### ISSUE TITLE
"tweet" parameter in /post documentation doesn't work as described

### ISSUE THREAD

**Issue by JPLeBreton** [tumblr/docs#23]
According to [this page](https://github.com/tumblr/docs/blob/master/api.md#post--create-a-new-blog-post-legacy), the "tweet" parameter

> Manages the autotweet (if enabled) for this post: set to off for no tweet, or enter text to override the default tweet

Up until about 3 years ago, I had a Python program that used the Tumblr API to submit draft posts with custom tweet text. Then one day, the tweet text stopped working, and the "tweet preview" text shown in the dashboard viewing the draft showed the main post text instead. I filed this issue:

https://github.com/tumblr/pytumblr/issues/100

Another user verified that the data was being sent correctly through the HTTP request, and that the particular library I was using wasn't at fault. Today I was able to reproduce the issue exactly as 3 years ago with both my minimal Python example code and the other user's Ruby example code, provided in that issue. So it would appear that something is going wrong on the Tumblr side.

**Comment by cyle** [comment]
Hey @JPLeBreton -- I've been able to reproduce this issue, looks like we did break this a few years ago. We'll see what we can do. 👌

**Comment by cyle** [comment]
This should be resolved now, and work as the documentation outlines. Please feel free to [open a Support Request with us](https://www.tumblr.com/support) if it doesn't work correctly, or comment here!
