### ISSUE TITLE
NPF post creation routes give unclear errors

### ISSUE THREAD

**Issue by invalidCards** [tumblr/docs#24]
The legacy post creation routes give a human-readable error if something goes wrong, such as "Invalid post id or reblog key" or "You cannot queue more than 300 posts". However, the NPF routes always give a 400 Bad Request error without any explanation of what has gone wrong. Is there a possibility to bring this back?

**Comment by cyle** [comment]
> Is there a possibility to bring this back?

Yup! Definitely. We should already be sending up some of this kind of data (including limits) via the error subcodes [available in the responses on the route](https://github.com/tumblr/docs/blob/master/api.md#errors-and-error-subcodes) -- or are you not seeing those in the response?

**Comment by invalidCards** [comment]
In browser scripts, getting non-2xx codes throws an error, rather than getting a return value back. These browser errors only state "Bad Request" for HTTP 400, without further explanation about what goes wrong. The return value will not be accessible (both with and without a try/catch block) and thus also no detailed information. I believe it does include a numerical error code, but that on its own doesn't say much.

**Comment by nightpool** [comment]
@invalidCards I think you're getting confused by the apiFetch helper—error responses don't normally throw an error in browser scripts. Here's an example of how this works with just normal fetch:

```js
// with normal fetch
fetch('https://www.tumblr.com/api/v2/user/info').then(r => r.json()).then(j => console.log(j.errors[0]))
// { title: "Unauthorized", code: 0, detail: "Tumblr went thud. Try again." }

// with the apiFetch helper
tumblr.apiFetch('/v2/blog/test-10/posts').catch(x => console.log(x.body.response));
// You do not have permission to view this blog
```

hope that helps!

**Comment by invalidCards** [comment]
This is the error body I get when omitting the `reblog_key` in an apiFetch call to `POST /v2/blog/{my blog here}/posts`:
![image](https://user-images.githubusercontent.com/842080/90409712-cbb5b700-e0a9-11ea-8745-5ebd30e419a4.png)

**Comment by nightpool** [comment]
I think omitting the reblog_key is a niche enough case that we probably don't _need_ to have a specific error message for it, even if it would be nice—weren't you having an issue with the queue limit? can you reproduce that?

**Comment by invalidCards** [comment]
@nightpool I am using it as an example right now because this also shows a disrepancy between the legacy routes and the NPF ones - legacy routes return a message stating "post id or reblog key not valid", which is completely missing here.
I will try to see what happens when I hit the queue limit once I get home, which should be in 20 minutes or so.

**Comment by nightpool** [comment]
> legacy routes return a message stating "post id or reblog key not valid"

Thanks, that was the additional context I was missing—it wasn't clear to me even as someone who has developed pretty extensively with the legacy API :P

I think part of this might be an intentional split between user-facing and developer-facing error messages though. The [detailed error codes cyle linked](https://github.com/tumblr/docs/blob/master/api.md#errors-and-error-subcodes) say that 8002 is "the reblog parent post and/or blog is invalid or cannot be found", which could be a little clearer but seems to match the "post id or reblog key not valid" error pretty closely.

**Comment by cyle** [comment]
Yeah I can try to make this clearer and expose more to the clients. 👍

**Comment by cyle** [comment]
Hopefully this helps you out! https://github.com/tumblr/docs/commit/0350fc11432fd3b0c8bf9368ac8920615a7efef9 And I think I fixed up some other potential cases where we were sending back the wrong code there.

Feel free to open another issue if something doesn't behave as you expect now.
