### ISSUE TITLE
Web Platform: document when apiFetch rejects

### ISSUE THREAD

**Issue by AprilSylph** [tumblr/docs#25]
Given that the documentation mentions that `apiFetch` uses the native `fetch` function, it would be useful if the difference in resolve/reject behaviour between the two was documented as well.

It's obvious that `apiFetch` doesn't resolve or reject with an actual **`Response`** object just from using it, but native **`fetch()`** doesn't reject at all if the *request* was successful, regardless of if the server responds with an OK status code. I assume `apiFetch` is rejecting when the internal `fetch`'s `Response.ok` is false, but this behaviour is unclear/unexpected until you get a non-OK response for the first time, and there's no documentation to point to if, for example, someone [mistakenly implements OK checking](https://github.com/AprilSylph/XKit-Rewritten/pull/4/files#r474739409) when `apiFetch` has already resolved.

**Comment by cyle** [comment]
Yup, good call. 👍  We'll update the docs to make this clearer.

**Comment by AprilSylph** [comment]
(resolved by 818991a)
