### ISSUE TITLE
Ambiguity about "content" parameter when reblogging a post using the NPF API

### ISSUE THREAD

**Issue by invalidCards** [tumblr/docs#26]
The API docs describe the `content` parameter to be required in a ` POST /v2/blog/{blog-identifier}/posts` call. While this makes sense to create a new post from scratch, if passing this parameter when reblogging with the contents of the post to reblog there is a chance that the content is duplicated. Please update the docs to mention that passing the `content` parameter is ONLY required if the post being created is brand new and not a reblog.

**Comment by cyle** [comment]
Yup, I can see how that's confusing. For new posts, it is obviously required, and you're correct that it's not required for reblogs, except if you want to add commentary in your reblog. We'll fix this up. 👍  Thanks!

**Comment by cyle** [comment]
Hopefully this should clear this up: https://github.com/tumblr/docs/commit/e16100abd6d4d6ecfa36f85a3ba763baecb408a7

Thanks again for calling this out!
