### ISSUE TITLE
Did tumblr change the way it's processing photos?

### ISSUE THREAD

**Issue by skillmatic-co** [tumblr/docs#28]
I haven't uploaded in a while (maybe since earlier this year or maybe late 2019).

I noticed with an upload tonight that my {PhotoURL-HighRes} is still pulling the correct dimensions photo, the but the quality is awful, it definitely appears to be super lossy compression or something. Has something recently changed from within on how Tumblr is processing uploads and displaying high res images? The quality of my uploads has drastically been reduced.

**Comment by cyle** [comment]
Hey @skillmatic-co, I don't think anything has changed, can you provide some examples?

**Comment by cyle** [comment]
Hey @skillmatic-co , this issue has been open 20 days, if you have some examples, please open a support request at tumblr.com/support -- as far as I'm aware, nothing has changed about our image processing pipeline recently.
