### ISSUE TITLE
Chat Messages

### ISSUE THREAD

**Issue by calves07** [tumblr/docs#29]
Hey, is there any way to retrieve chat messages using the API or is it possible to implement this feature?

**Comment by cyle** [comment]
Hello @calves07  -- at this time, there is no way to retrieve chat messages (via group chats or direct messages) via the public API. If this changes, you'll see an update here in this repo in our API docs!

In the meantime, you should be able to export your messages/conversations via the [blog export tool](https://tumblr.zendesk.com/hc/en-us/articles/360005118894-Export-your-blog). If you run into any issues with that, please [reach out to support](https://www.tumblr.com/support).
