### ISSUE TITLE
Color(s) field name ambiguity

### ISSUE THREAD

**Issue by highthunder** [tumblr/docs#3]
In the NPF documentation for Image content blocks it says:
> Image blocks may contain a `color` field
However, in both the example and table below that paragraph, the field name is shown as `colors`.

**Comment by cyle** [comment]
Thanks for calling this out! We've fixed this (and a handful of other typos and discrepancies) in the latest commit https://github.com/tumblr/docs/commit/d7249d9f50d85ab3601fb2f199b3f2c48ee13c22
