### ISSUE TITLE
NPF and archive post types

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#31]
I'm a bit confused about the NPF. 
Right now we can still create old style posts where you set the post type. Then in archive you can filter by post type and there it is.
If I create a post from the mobile app, it will be NPF (I assume) because I cannot select the type by hand. How will it show in the archive? If I put only one picture? If I put a text and a picture? If I put a picture and a text? And a URL in the end? Does the archived type depend on its structure? Or on the first element? Will a text+picture post will show both under the text filter AND the picture filter? Is there a consistent way to decide the type? What should be my expectations?
`</confused>`

**Comment by nightpool** [comment]
hi sorin! this is covered by the NPF docs, in the [Mapping NPF Post Content to Legacy Post Types](https://www.tumblr.com/docs/npf#mapping-npf-post-content-to-legacy-post-types) section. 

hope that helps! lmk if you have any other questions

**Comment by sorin-costea** [comment]
Great summary, thank you! However that doesn't explain the archive page - is that organized by legacy post type? Or will a post with more content blocks appear in more than one category?

**Comment by AprilSylph** [comment]
Posts only get mapped to one legacy post type, as defined by the order of the rules in the map. So, an NPF post with both video and photo blocks will get mapped/categorised as being a legacy video post, since the criteria for a post being mapped as a video post comes before the criteria for being mapped as a photo post.

**Comment by sorin-costea** [comment]
Cool, so archived by legacy post type. Thank you!
