### ISSUE TITLE
API clients look a bit... abandoned

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#32]
Probably not the perfect place to ask, but could you comment a bit on the status of the API clients? For instance, Jumblr (the Java client) has PRs open since 2013 and got in 2019 only a readme update... are there any plans to at least have a look at them?

**Comment by sorin-costea** [comment]
Anybody, please?

**Comment by cyle** [comment]
Hi @sorin-costea -- we saw this. We're discussing internally what the best course of action is here.

**Comment by sorin-costea** [comment]
You could also ask the community for help... Thank you anyway!

**Comment by cyle** [comment]
Hey @sorin-costea -- sorry for taking so long to reply to this fully. We're now planning to evaluate our existing API clients available here on GitHub and take action on them based on what we feel we can actively support, and deprecate/drop official support for what we can't. We'll update the corresponding repos as we make those evaluations. Also, hopefully soon we'll be publishing more updates to our API docs here, along with some API guides on [our Engineering blog](https://engineering.tumblr.com).
