### ISSUE TITLE
No documentation of nested lists

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#33]
Today's changelog entry indicates:
>  - Displaying nested lists in posts is now supported in the Tumblr mobile apps as of version 17.0.

However, there's no documentation on how this might be achieved in the NPF spec, which still says:

> Note that NPF **does not allow nested lists or non-text-based lists** at this time.

This seems like a deficiency that should be corrected!

**Comment by cyle** [comment]
Thanks @nightpool for calling this out! We'll be updating our NPF specs to reflect this change.

**Comment by cyle** [comment]
There's now some documentation on nested lists as per [this commit](https://github.com/tumblr/docs/commit/e609ff77e98bd27cc26ad4301745489cc0aba4a3) -- feel free to open a new issue with questions if you have any!

**Comment by nightpool** [comment]
thank you Cyle!
