### ISSUE TITLE
Tumblr export option missing photos / mis-linking photos.

### ISSUE THREAD

**Issue by madCode** [tumblr/docs#37]
I just downloaded an export of a tumblr blog of mine and noticed two problems:
1. Sometimes posts are missing photos.
e.g. if there's a post named 123456789.html and a photo in the media folder named 123456789.gif, the post html doesn't contain the photo in it. I checked the raw html and there isn't even an empty img html tag. There's just nothing. The text and tags of the post render fine, but the photo is missing.

2. Sometimes posts link to the wrong photo.
e.g. Say there are two posts, 1.html and 2.html. And two photos: 1.gif, and 2.gif. 2.html embeds 1.gif in it instead of 2.gif.

**Comment by cyle** [comment]
Hello @madCode  -- unfortunately this is not the best venue for issues with the Tumblr export blog tool. Please file a support ticket at https://www.tumblr.com/support and we'll help you as much as we can! This repo is meant for issues/questions about the Tumblr API.

**Comment by madCode** [comment]
Thanks @cyle ! I'll be sure to do that :)
