### ISSUE TITLE
Can not create post using the NPF format.

### ISSUE THREAD

**Issue by jaggerwang** [tumblr/docs#4]
It always response "400 Bad Request"! I checked the post body format for hundreds of times, and can not see where is wrong. I can not post on your google group, and find where to submit a issue!

Here is my request body.

```
--TumblrBoundary
Content-Disposition: form-data; name="json"
Content-Type: application/json

{"content":[{"media":[{"height":101,"identifier":"file0","type":"image/jpeg","width":82}],"type":"image"}]}
--TumblrBoundary
Content-Disposition: form-data; name="file0"; filename="syl-logo.jpg"
Content-Type: image/jpeg

<binary image data>
--TumblrBoundary--
``

**Comment by jaggerwang** [comment]
The response body is `{{400 Bad Request} [map[title:Bad Request code:8001 detail:Posting failed. Please try again.]] []}`.

**Comment by cyle** [comment]
Sorry for the super late response @jaggerwang but your content block doesn't have a `type`, as required by the [NPF content block spec](https://github.com/tumblr/docs/blob/master/npf-spec.md#content-blocks) -- it looks like if you put `"type": "image"` in that first content block, it should work.
