### ISSUE TITLE
OAuth 2.0 Support

### ISSUE THREAD

**Issue by ThisIsMissEm** [tumblr/docs#42]
Currently the Tumblr API relies on OAuth 1.0a for authentication and flows, instead of the more modern OAuth 2.0 specification. With OAuth 2.0 now being eight years old, and OAuth 1.0a often being considered less secure, and has fewer supported features (for instance, it doesn't support non-web based flows), it'd be good to upgrade.

There's a good comparison found here, but I do understand this would likely be a significant amount of engineering work.

**Comment by cyle** [comment]
Agreed. We actually already have OAuth 2.0 support built, it's just not released to third party API consumers yet. When we do, we'll post about it on [the Changes blog](https://changes.tumblr.com/). Thanks for the suggestion!
