### ISSUE TITLE
Something fishy with for /user/follow - fails but with HTTP 200

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#44]
When calling `/user/follow` with some okay blog (not sensitive, very public, everything normal) I get the following response:
```
{
  "meta": {
    "status": 200,
    "msg": "OK"
  },
  "response": {
    "blog": {
      "ask": true,
      "ask_anon": true,
      "ask_page_title": "...",
      "asks_allow_media": true,
      "avatar": [
		{...}
      ],
      "can_chat": true,
      "can_send_fan_mail": false,
      "can_subscribe": false,
      "description": "...",
      "followed": false,
      "is_blocked_from_primary": false,
      "is_nsfw": false,
      "likes": 2880,
      "name": "...",
      "posts": 26783,
      "share_likes": true,
      "subscribed": false,
      "theme": {...},
      "title": "...",
      "total_posts": 26783,
      "updated": 1615809420,
      "url": "https://....tumblr.com/",
      "uuid": "t:..."
    }
  }
}

```

Notice? It says `followed=false`. So the operation actually failed even though it answered 200. The headers look okay as well:
```
X-Ratelimit-Perhour-Remaining=980
X-Ratelimit-Perhour-Reset=3343
X-Ratelimit-Perhour-Limit=1000
X-Ratelimit-Perday-Remaining=4893
X-Ratelimit-Perday-Reset=81297
X-Ratelimit-Perday-Limit=5000
```

so... there must be something wrong in the documentation some place...

**Comment by cyle** [comment]
> Notice? It says followed=false. 

This is most likely just a [race condition](https://en.wikipedia.org/wiki/Race_condition) on our side, i.e. the record being saved to indicate you now follow that blog is written a microsecond _after_ we query to see if you're following that blog when we render that JSON. We can fix it on our side. 👍  Thanks for bringing it to our attention!

**Comment by sorin-costea** [comment]
I'm totally happy to help getting Tumblr better :) but unfortunately that user is still not followed even now after a day (just checked on my dash), so it must have been something else...

**Comment by sorin-costea** [comment]
@cyle could it rather be the 200 follows/day quota being applied?

**Comment by cyle** [comment]
> @cyle could it rather be the 200 follows/day quota being applied?

This is possible, though the Tumblr API should be throwing a `4xx` status code (most likely `403 Forbidden`) at you in that case, not a `200 OK`. I'll update this with more info when we've figured it out. 👌

**Comment by cyle** [comment]
Sorry for not getting to this much sooner -- the issue should be resolved now, `followed` should be `true` in the response after a successful follow.
