### ISSUE TITLE
The POST /user/filtered_content examples don't work

### ISSUE THREAD

**Issue by StillLynnTheCloset** [tumblr/docs#45]
The examples for POST show a plaintext format:
```
POST https://api.tumblr.com/v2/user/filtered_content
filtered_content=something

POST https://api.tumblr.com/v2/user/filtered_content
filtered_content[0]=something&filtered_content[1]=technology
```
However, these requests return a 400 error. 

After some trial and error, I determined that the requests that do work use a JSON format:
```
POST https://api.tumblr.com/v2/user/filtered_content
{"filtered_content":"something"}

POST https://api.tumblr.com/v2/user/filtered_content
{"filtered_content":["something","technology"]}
```

**Comment by AprilSylph** [comment]
The web client uses form data as the first example shows... are you maybe omitting `Content-Type: application/x-www-form-urlencoded; charset=UTF-8` in the request headers?

**Comment by StillLynnTheCloset** [comment]
Ah, that's where the disconnect is, I'm implementing a client library, so I'm expecting API calls to be a standard post request.
If the web client uses a different request format, that should probably be documented on the web client documentation and not in the standard API documentation with all of the other JSON based APIs .

**Comment by cyle** [comment]
Hello! Thanks for pointing this out. @AprilSylph is correct: this endpoint expects `Content-Type: application/x-www-form-urlencoded`, not `Content-Type: application/json`. Most of the Tumblr API endpoints can accept either, but in some cases, like creating NPF posts, they can only accept one format. We'll update the documentation to make this clearer.

**Comment by StillLynnTheCloset** [comment]
But the API currently _does_ support `application/json` requests for POST, GET, and DELETE, is that unintentional functionality that will be removed?

**Comment by cyle** [comment]
> But the API currently _does_ support `application/json` requests for POST, GET, and DELETE, is that unintentional functionality that will be removed?

No, definitely not. I just meant that we'll be clarifying these different acceptable `Content-Type` headers -- `application/json` is one of them. 👌  The core problem I think you've uncovered is that _not providing the header at all_ can lead to unexpected behavior, as you saw.

**Comment by StillLynnTheCloset** [comment]
Actually, I always provided a header, but for my first attempts it was `text/plain`.

I'll update my PR to show both.

**Comment by cyle** [comment]
We'll be pushing an update to the docs soon with a new top level section on valid `Content-Type` values across all endpoints that expect body parameters.

**Comment by cyle** [comment]
Docs have been updated in the latest commit to explicitly mention how `Content-Type` headers are expected to work: https://github.com/tumblr/docs/commit/c08e8e97df1dfbbc150e062e4a650d50e9bfd3f8

Thanks again for raising this issue, and sorry it was confusing!
