### ISSUE TITLE
status of web-platform

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#47]
is `web-platform.md` supposed to be published anywhere, or is this repo the authoritative reference for it? https://www.tumblr.com/docs/web-platform does not seem to work, nor do several other common spellings for it

**Comment by cyle** [comment]
This repo is the authoritative reference for it, it's not meant to be duplicated anywhere else on tumblr.com presently.

**Comment by nightpool** [comment]
thanks for the confirmation! just trying to make sure i have the write URL written down in my docs
