### ISSUE TITLE
Unexpected results from Video Object

### ISSUE THREAD

**Issue by shoshi** [tumblr/docs#5]
For a post that contains an updated vimeo URL, the API response returned conflicting IDs:
```js
{
  type: 'video',
  provider: 'vimeo',
  url: 'https://player.vimeo.com/video/326576684',
  embed_url: 'https://player.vimeo.com/video/325672146?title=0&byline=0&portrait=0&app_id=122963',
  metadata: { id: '326576684' }
}
```

**Expected:**
All Vimeo IDs to use the updated ID `326576684`.

**Actual:**
The `embed_url` contained the original (incorrect) Vimeo ID: `325672146`. `url` and `metadata.id` contain the new (correct) ID.

This seems to be a bug in the old post format, as well. The results from that returned:
```<figure class="tmblr-embed tmblr-full" data-provider="vimeo" data-orig-width="540" data-orig-height="304" data-url="https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F326576684"><iframe src="https://player.vimeo.com/video/325672146?title=0&amp;byline=0&amp;portrait=0&amp;app_id=122963" width="540" height="304" frameborder="0" title="Save The Internet Act Markup" allowfullscreen=""></iframe></figure>```

**Expected:**
All Vimeo IDs to use the updated ID `326576684`.

**Actual:**
The `data-url` has the new (correct) ID, but the `iframe src` contains the old (incorrect) ID.

**Comment by cyle** [comment]
Hey @shoshi, sorry for the late reply! Is this happening when creating a new post or editing an existing post? We send along Vimeo embeds to [Vimeo's OEmbed Service](https://developer.vimeo.com/api/oembed), so it's very possible that's what's returning the mismatched ID, but it may depend on if this is a new post or editing an existing post.

**Comment by cyle** [comment]
Closing this issue, please feel free to re-open if the problem persists and/or you have more information.
