### ISSUE TITLE
tumblr.apiFetch does not correctly interpret queryParams as supplied by API response

### ISSUE THREAD

**Issue by AprilSylph** [tumblr/docs#50]
I'm trying to gather user likes via the New Web Platform's [`tumblr.apiFetch()`](https://github.com/tumblr/docs/blob/master/web-platform.md#apifetch) method. Supplying only the resource (`'/v2/user/likes'`) and looping using the response's `response.links.next.href` value works imperfectly, so I tried specifying `queryParams` with the same values that the web client does. However, pulling `queryParams` from the response's `link.next` object does not work as expected.

---

```js
(async () => {
  const resource = '/v2/user/likes';
  let queryParams = {
    'fields[blogs]': 'name,avatar,title,url,is_adult,?is_member,description_npf,uuid,can_be_followed,?followed,?advertiser_name,theme,?primary,?is_paywall_on,?paywall_access,?subscription_plan',
    limit: 21,
    reblog_info: true
  };
  
  while (queryParams) {
    const { response } = await window.tumblr.apiFetch(resource, { queryParams });
    // Do stuff with response.likedPosts
    queryParams = response.links?.next?.queryParams;
  }
})();
```

First request URL (with manually-specified `queryParams`): `https://www.tumblr.com/api/v2/user/likes?fields%5Bblogs%5D=name%2Cavatar%2Ctitle%2Curl%2Cis_adult%2C%3Fis_member%2Cdescription_npf%2Cuuid%2Ccan_be_followed%2C%3Ffollowed%2C%3Fadvertiser_name%2Ctheme%2C%3Fprimary%2C%3Fis_paywall_on%2C%3Fpaywall_access%2C%3Fsubscription_plan&limit=21&reblog_info=true` 

First response `links`:
```json
{
	"next": {
		"href": "/v2/user/likes?fields%5Bblogs%5D=name%2Cavatar%2Ctitle%2Curl%2Cis_adult%2C%3Fis_member%2Cdescription_npf%2Cuuid%2Ccan_be_followed%2C%3Ffollowed%2C%3Fadvertiser_name%2Ctheme%2C%3Fprimary%2C%3Fis_paywall_on%2C%3Fpaywall_access%2C%3Fsubscription_plan&limit=21&reblog_info=true&before=1624634022",
		"method": "GET",
		"queryParams": {
			"fields": {
				"blogs": "name,avatar,title,url,is_adult,?is_member,description_npf,uuid,can_be_followed,?followed,?advertiser_name,theme,?primary,?is_paywall_on,?paywall_access,?subscription_plan"
			},
			"limit": "21",
			"reblogInfo": "true",
			"before": "1624634022"
		}
	}
}
```

Second request URL (using API-supplied `queryParams`): `https://www.tumblr.com/api/v2/user/likes?fields=%5Bobject%20Object%5D&limit=21&reblogInfo=true&before=1624634022`

---

The `apiFetch()` `queryParams` documentation states "This will encode the params and append them to the request URL, so you don't need to do that yourself", but this is evidently not true when using API response `queryParams`, as any object-type value is *not* converted to an acceptable format and is instead directly converted to string - completely discarding any data within.

Tangientally related to #43 since the Tumblr API's custom format for object/array-type parameters is involved.

**Comment by cyle** [comment]
> The apiFetch() queryParams documentation states "This will encode the params and append them to the request URL, so you don't need to do that yourself", but this is evidently not true when using API response queryParams, as any object-type value is not converted to an acceptable format and is instead directly converted to string - completely discarding any data within.

Looks like you found a bug with this! We're taking a look internally and we'll either fix this up so it does work as expected (and as indicated in the docs) or we'll update the docs with the best path forward here.

**Comment by dmsnell** [comment]
@AprilSylph this should hopefully be fixed now - mind checking to confirm that what we updated is what you noticed and expected?

**Comment by AprilSylph** [comment]
Yep, looks good; thanks!
