### ISSUE TITLE
Documentation issue with /oauth/request_token

### ISSUE THREAD

**Issue by ThisIsMissEm** [tumblr/docs#55]
When issuing the `POST /oauth/request_token` request, the API docs state that the response:
- should be in JSON, if `Content-Type` is set to `application/json`, but I'm getting back URL encoded data for some reason?
- there should be two values returned `oauth_token` and `oauth_token_secret`, but I'm also seeing a third value returned for a `oauth_callback_confirmed` which seems to just be `"true"`?

Should these properties of the API be documented?

**Comment by sndsgd** [comment]
Thanks for creating this issue :ok_hand: 

> should be in JSON, if Content-Type is set to application/json

Can you clarify what you mean here? The endpoint should always return `application/x-www-form-urlencoded` as defined by the spec, and in my testing the response `Content-Type` is never `application/json`.

We'll merge an update to include the `oauth_callback_confirmed` response property, and indicate the response content type is `application/x-www-form-urlencoded`. Please let me know if that'll cover the items in this issue.

**Comment by ThisIsMissEm** [comment]
Oh! Interesting!

I must've missed that in my fairly loose implementation of oauth 1.0a; I can see that I'm meant to send data via `x-www-form-urlencoded` (or query params), but if I send with `Accept: application/json` or `Content-Type: application/json` then the server doesn't reject the request, instead it just returns back `application/x-www-form-urlencoded` responses.

I'd been sending requests all with `Accept: application/json`, and was confused when I got back a different content-type; Perhaps returning a `406 Not Acceptable` error if the `Accept` is sent and it is not `application/x-www-form-urlencoded` would be appropriate?

JSON APIs have spoiled me 😆

**Comment by sndsgd** [comment]
Thanks for clarifying! We just merged an update to the docs: https://github.com/tumblr/docs/commit/ef3f1b1491ce49da4e3a3f9bd9db2858ebf64300, but I'll keep this issue open until we also implement the 406 response for the applicable routes :ok_hand:

**Comment by nightpool** [comment]
I'm a little worried that the 406 response is going to be a breaking change
for clients that were unknowingly setting the Accept header previously. Do
you have any stats on how frequently this misconfiguration happens?

**Comment by sndsgd** [comment]
Over the past few weeks we've had more than a handful of requests made to the `/oauth/...` endpoints with invalid accept headers. In the spirit of not breaking existing implementations we will not be introducing further changes at this time.

**Comment by ThisIsMissEm** [comment]
If those requests came from a german IP address, they'd be me — but otherwise not me. Just in case that affects your stats & decisions 

Emelia
