### ISSUE TITLE
API Methods return an undocumented 303 redirect for privacy consent

### ISSUE THREAD

**Issue by ThisIsMissEm** [tumblr/docs#56]
Despite using tumblr as a user, and having followed the privacy consent dialog, after authorising with the API, the API returns back responses to methods such as `/v2/user/dashboard` and `/v2/user/info` as being 303 Redirects to the privacy consent page.

An example response was:

```
{
  status: 303,
  headers: {
    server: 'nginx',
    date: 'Tue, 24 Aug 2021 15:54:38 GMT',
    'content-type': 'text/html; charset=UTF-8',
    'content-length': '0',
    connection: 'keep-alive',
    'x-rid': '07f571380157b5900ef081e5908e4c6c',
    p3p: `CP="Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy"`,
    location: 'https://www.tumblr.com/privacy/consent/begin?redirect=https%3A%2F%2Fwww.tumblr.com%2Fv2%2Fuser%2Fdashboard',
    'x-ua-compatible': 'IE=Edge,chrome=1',
    'strict-transport-security': 'max-age=31536000; preload'
  },
  body: ''
}
```

Whilst I've been writing my own API client in node.js (instead of using the official one), I can't find anything in the official one's source code as to how to deal with this either, so I think it's affecting there too.

This would mean your API has been broken for requests originating from within the EU for however long the cookie consent banner has been in place. I haven't been able to test from the US (ex. california) yet, as my VPN provider is having issues.

**Comment by ThisIsMissEm** [comment]
Actually, I've figured it out, and it was totally my bad.

I'd been implementing the OAuth 1.0a flow in my client, and had set the base URL to `https://www.tumblr.com/` because of that, instead of `https://api.tumblr.com/` 🤦‍♀️ 

From a DX perspective, it could make sense to just 404 all `/v1` or `/v2` URLs on `https://www.tumblr.com` with the message that the tumblr API isn't located at the same URL as the OAuth server, or something.

**Comment by cyle** [comment]
> From a DX perspective, it could make sense to just 404 all `/v1` or `/v2` URLs on `https://www.tumblr.com` with the message that the tumblr API isn't located at the same URL as the OAuth server, or something.

Thanks for the suggestion! We'll consider this. 👍
