### ISSUE TITLE
GET `/v2/blog/{blog-identifier}/posts/{post-id}` doesn't return scheduled post data

### ISSUE THREAD

**Issue by AprilSylph** [tumblr/docs#63]
When fetching a post (Neue Post Format), there is no differentiation between a queued post and a scheduled post. It appears that the correct way to schedule a post is simply to use `state: "queue"` and include a valid `publish_on` string, but the latter is nowhere to be seen when fetching the resulting post - making it apparently impossible to edit a post without discarding its previous scheduled publish time.

I don't see a way to retain (or even see) a post's scheduled time at all, but if I'm missing something, I would greatly appreciate if the intended way to edit scheduled posts could be documented.

<details>
<summary>POST <code>https://www.tumblr.com/api/v2/blog/t:ZUokygnCFFXuafJ0bADDUQ/posts</code></summary>

Request:
```json
{
	"content": [
		{
			"subtype": "heading1",
			"text": "",
			"type": "text"
		},
		{
			"formatting": [],
			"text": "schedule me captain",
			"type": "text"
		}
	],
	"hide_trail": false,
	"publish_on": "2021-11-08T16:10:00.000Z",
	"state": "queue",
	"tags": ""
}
```

Response:
```json
{
	"meta": {
		"status": 201,
		"msg": "Created"
	},
	"response": {
		"id": "667300496291282944",
		"state": "queued",
		"displayText": "Scheduled post."
	}
}
```
</details>

<details>
<summary>GET <code>https://www.tumblr.com/api/v2/blog/t:ZUokygnCFFXuafJ0bADDUQ/posts/667300496291282944</code></summary>

Response:
```json
{
	"meta": {
		"status": 200,
		"msg": "OK"
	},
	"response": {
		"objectType": "post",
		"type": "blocks",
		"id": "667300496291282944",
		"tumblelogUuid": "t:ZUokygnCFFXuafJ0bADDUQ",
		"originalType": "regular",
		"blogName": "aprilsylph",
		"blog": {
			"name": "aprilsylph",
			"title": "CODEGIRL",
			"description": "April's secondary account for testing stuff",
			"url": "https://aprilsylph.tumblr.com/",
			"uuid": "t:ZUokygnCFFXuafJ0bADDUQ",
			"updated": 1636387297,
			"key": "bmUScV56O",
			"theme": {
				"headerFullWidth": 627,
				"headerFullHeight": 352,
				"headerFocusWidth": 626,
				"headerFocusHeight": 352,
				"avatarShape": "circle",
				"backgroundColor": "#F6F6F6",
				"bodyFont": "Helvetica Neue",
				"headerBounds": "0,626,352,0",
				"headerImage": "https://64.media.tumblr.com/422a834280cf65560a5b11c982ce15ac/9f530942c070ac6c-65/s627x352/56a6f4ff4d4fde2d19f675f5fbb157946f709606.png",
				"headerImageFocused": "https://64.media.tumblr.com/422a834280cf65560a5b11c982ce15ac/9f530942c070ac6c-65/s2048x3072_c0,0,99841,100000/0095b1f3a8a77296c86828898656c7983ff7ddf8.png",
				"headerImagePoster": "",
				"headerImageScaled": "https://64.media.tumblr.com/422a834280cf65560a5b11c982ce15ac/9f530942c070ac6c-65/s2048x3072/d7a56dce3ec9cffa9aa5778dfa94de17e1eadc0d.png",
				"headerStretch": true,
				"linkColor": "#A77DC2",
				"showAvatar": false,
				"showDescription": true,
				"showHeaderImage": true,
				"showTitle": true,
				"titleColor": "#cd64ff",
				"titleFont": "Typewriter FS",
				"titleFontWeight": "regular"
			},
			"canMessage": true,
			"canChat": false,
			"shareLikes": true,
			"shareFollowing": true,
			"isNsfw": false,
			"isAdult": false,
			"canBeFollowed": false,
			"placementId": ""
		},
		"isNsfw": false,
		"classification": "clean",
		"ownerFlaggedNsfw": false,
		"ownerFlaggedSensitive": false,
		"ownerAppealNsfw": "none",
		"nsfwScore": 0,
		"idString": "667300496291282944",
		"postUrl": "https://aprilsylph.tumblr.com/private/667300496291282944/tumblr_r29gk0WWRk1twc1ie",
		"slug": "schedule-me-captain",
		"date": "2021-11-08 16:02:24 GMT",
		"timestamp": 1636387344,
		"state": "queued",
		"reblogKey": "0jXn4re0",
		"tags": [],
		"shortUrl": "https://tmblr.co/ZrPW1ob2kaGFua00",
		"summary": "schedule me captain",
		"shouldOpenInLegacy": false,
		"recommendedSource": null,
		"recommendedColor": null,
		"followed": false,
		"liked": false,
		"noteCount": 0,
		"likeCount": 0,
		"reblogCount": 0,
		"replyCount": 0,
		"content": [
			{
				"type": "text",
				"text": "schedule me captain"
			}
		],
		"layout": [],
		"trail": [],
		"canEdit": true,
		"canDelete": true,
		"canReply": false,
		"canLike": false,
		"interactabilityReblog": "everyone",
		"canReblog": false,
		"canSendInMessage": false,
		"canPin": false
	}
}
```
</details>

**Comment by cyle** [comment]
Hello April! This is indeed a bit confusing. A couple of things: 

Currently, you can simply omit the `publish_on` parameter when editing a scheduled/queued post, and it won't change its scheduled time to post. You can see this in action when editing a queued or scheduled post on the web; we don't pass along that `publish_on` field when sending the `PUT` request. The API will simply assume you don't want to change the order of your queue or when the post should be scheduled.

But it's true that there is no indication in the Post JSON whether the post is _queued_ or _scheduled_, or what the scheduled time is -- this looks like a bug on our end. There should be additional fields to indicate such:

- `queued_state` with either `queued` or `scheduled`.
- `scheduled_publish_time` should be present if `scheduled`, with the timestamp of when it should be posted.

I'll work on fixing that up for you. Note that those fields are read-only. Changing their values should still be done via changing the post's `state` and `publish_on` fields, if you want to change them.

**Comment by AprilSylph** [comment]
> Currently, you can simply omit the `publish_on` parameter when editing a scheduled/queued post, and it won't change its scheduled time to post.

I see. This is not the behaviour I'm observing, however. Just now, I scheduled a post for 09:00, 10th December 2021, then edited it, omitting `publish_on`.

<details>
<summary>POST <code>https://www.tumblr.com/api/v2/blog/t:QMhm_aldjr-B68bY-2ietA/posts</code></summary>

Request:

```json
{
	"content": [
		{
			"subtype": "heading1",
			"text": "",
			"type": "text"
		},
		{
			"formatting": [],
			"text": "schedule this post for 2021-12-10T09:00Z",
			"type": "text"
		}
	],
	"hide_trail": false,
	"publish_on": "2021-12-10T09:00:00.000Z",
	"send_to_twitter": false,
	"state": "queue",
	"tags": ""
}
```

Response:

```json
{
	"meta": {
		"status": 201,
		"msg": "Created"
	},
	"response": {
		"id": "667310229437005824",
		"state": "queued",
		"displayText": "Scheduled post."
	}
}
```
</details>

<details>
<summary>PUT <code>https://www.tumblr.com/api/v2/blog/t:QMhm_aldjr-B68bY-2ietA/posts/667310229437005824</code></summary>

Request:

```json
{
	"content": [
		{
			"text": "schedule this post for 2021-12-10T09:00Z",
			"type": "text"
		}
	],
	"date": "2021-11-08 18:37:06 GMT",
	"hide_trail": false,
	"layout": [],
	"slug": "schedule-this-post-for-2021-12-10t0900z",
	"state": "queued",
	"tags": "oops i forgot to tag this"
}
```

Response:

```json
{
	"meta": {
		"status": 200,
		"msg": "OK"
	},
	"response": {
		"id": "667310229437005824",
		"state": "queued",
		"displayText": "Added to queue."
	}
}
```
</details>

As a result of the PUT, keeping `state: "queued"` and omitting `publish_on`, the post is now queued rather than scheduled, with my queue indicating it will be published tomorrow at 08:00.

**Comment by nightpool** [comment]
My guess is that you'd have to omit the "state" field from the PUT request
if you don't want to change the post's state

**Comment by AprilSylph** [comment]
Either way, the docs imply that no fields can be omitted, so that needs to be updated if that's true.

https://github.com/tumblr/docs/blob/ef47e3c/api.md#request-parameters-26
> For editing a post, all of the request parameters from the NPF Post Creation route are expected (depending on if it's an original post or reblog), along with the Post's ID in the query path.

**Comment by cyle** [comment]
Ah, you're correct. For scheduled posts, the `publish_on` field is indeed expected when you want the post to remain scheduled and not queued. So this should be resolve-able once the two fields I indicated are being sent to you. Reading through this again, I think the best course of action on my side is to just include `publish_on` as its own field as well, so you can just pass it through when making the `PUT`.

**Comment by cyle** [comment]
To summarize the upcoming changes to the Post object:

- `queued_state` with either "queued" or "scheduled".
- `scheduled_publish_time` should be present with the timestamp of when it should be posted, whether "queued" or "scheduled". (Tumblr uses this for display purposes.)
- `publish_on` should also be present when the `queued_state` is "scheduled". This value can safely be passed through when editing the post if you'd like to preserve the scheduled time.

So technically you'll be able to tell if a post with `state: queued` is queued or scheduled two ways:

- If `publish_on` is present in the Post object, then it's a scheduled post.
- By looking at the value of `queued_state`.

**Comment by cyle** [comment]
These fields should be available now! And we've updated the docs: https://github.com/tumblr/docs/commit/5a29ba8c062bd29cd2d26e4c6987a2c9349b5428
