### ISSUE TITLE
is there also a quota on unfollow?

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#64]
I think there is - I was trying to cleanup my followed list and now I'm getting 403 limit exceeded. Does it make sense to put quotas on unfollow??? I don't see what the spam can be, but anyway, can you please confirm this limit exists?

**Comment by cyle** [comment]
Hello!

> 403 limit exceeded

Are you getting a `403 Forbidden` or ` 429 Limit Exceeded` ? Or is our API actually sending you a `403` but the message is `Limit Exceeded` ? It should only be one or the other, not both. 🤔 

> can you please confirm this limit exists?

Yes -- there's a blanket rate limit on hitting our API, no matter the endpoint you're using. If you're getting a `429 Limit Exceeded` from the API, then you've hit that limit. There's documentation on these limits [here](https://github.com/tumblr/docs/blob/master/api.md#rate-limits).

**Comment by sorin-costea** [comment]
You're right it's 429 Limit exceeded. But the documentation doesn't say anything about a special limit on unfollow - and I got the message after unfollowing about 190 accounts. Definitely not the general API limit of 1000/hour.

**Comment by cyle** [comment]
Yeah, there is no special limit for unfollowing. You may be hitting this:

> 300 API calls per minute, per IP address.

If you're doing a lot of pagination through your following list and unfollowing in rapid succession. Also, if you're doing this on some kind of shared hosting service like AWS, you could be sharing an IP address with potentially bad actors (we've seen this case happen before).

If that's not it, I'd encourage you to [file a Support ticket](https://www.tumblr.com/support), including your API consumer info, so we can double-check what's going on here.

**Comment by sorin-costea** [comment]
Whoops, must be the minute thing - it's definitely doing it rapidly. I didn't even notice that limit existed... I only read the X-* headers and there's no X-Ratelimit-Perminute :D
Thank you, I'll close this and go re-read the docs.
