### ISSUE TITLE
api apparently requires the User-Agent header now

### ISSUE THREAD

**Issue by Yay295** [tumblr/docs#65]
About a month ago my posting script stopped working. I filed a support request on Tumblr and after some discussion they suggested adding a custom "User-Agent" header to my requests, and doing so has allowed me to submit posts using the API again. This header is not mentioned in the API documentation though. There's [a section in the documentation](https://github.com/tumblr/docs/blob/master/api.md#request-content-types) that mentions the "Content-Type" header being required, so a small section about adding a custom "User-Agent" header could probably be put in the same place.

The official Python client already sets this header (https://github.com/tumblr/pytumblr/blob/master/pytumblr/request.py#L32), so it's only necessary if you're doing things manually.

**Comment by cyle** [comment]
Thanks for calling this out! We've [added a section about this now](https://github.com/tumblr/docs/blob/master/api.md#request-user-agent).
