### ISSUE TITLE
following via API over limit, answers 200 ok yet fails

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#66]
You closed #44 as fixed, but although there was a change, it is arguably for worse.
Namely: if I get now over the 200 follows limit, then a new follow request will:
- answer HTTP 200
- set in the body the followed=true
- not reply with any API limit headers - at all
- in dashboard the blog will be seen as not followed (I have the "follow" button active)

No it's not a temporary delay also not a race condition, because half an hour later and few retries later the situation is the same: incorrect answer and action actually failing.

**Comment by sorin-costea** [comment]
{
	  "meta": {
		"status": 200,
		"msg": "OK"
	  },
	  "response": {
		"blog": {
		  "ask": true,
		  "ask_anon": true,
		  "ask_page_title": "",
		  "asks_allow_media": false,
		  "avatar": [
			{
			  "width": 512,
			  "height": 512,
			  "url": "https://64.media.tumblr.com/..."
			},
			{
			  "width": 128,
			  "height": 128,
			  "url": "https://64.media.tumblr.com/..."
			},
			{
			  "width": 96,
			  "height": 96,
			  "url": "https://64.media.tumblr.com/..."
			},
			{
			  "width": 64,
			  "height": 64,
			  "url": "https://64.media.tumblr.com/..."
			}
		  ],
		  "can_chat": false,
		  "can_send_fan_mail": false,
		  "can_subscribe": false,
		  "description": "<p>(...</p>",
		  "followed": true,
		  "is_blocked_from_primary": false,
		  "is_nsfw": false,
		  "name": "...",
		  "posts": 2935,
		  "share_likes": false,
		  "subscribed": false,
		  "theme": {
			"header_full_width": 1536,
			"header_full_height": 2048,
			"header_focus_width": 1414,
			"header_focus_height": 796,
			"avatar_shape": "circle",
			"background_color": "#3C2A2A",
			"body_font": "Helvetica Neue",
			"header_bounds": "318,1536,1114,122",
			"header_image": "https://64.media.tumblr.com/...",
			"header_image_focused": "https://64.media.tumblr.com/...",
			"header_image_poster": "",
			"header_image_scaled": "https://64.media.tumblr.com/...",
			"header_stretch": true,
			"link_color": "#888888",
			"show_avatar": true,
			"show_description": true,
			"show_header_image": true,
			"show_title": true,
			"title_color": "#888888",
			"title_font": "Grumpy Black 48",
			"title_font_weight": "bold"
		  },
		  "title": ".....",
		  "total_posts": 2935,
		  "updated": 1637625494,
		  "url": "https://....tumblr.com/",
		  "uuid": "..."
		}
	  }
	}

**Comment by sorin-costea** [comment]
{
	  "null": "HTTP/1.1 200 OK",
	  "X-UA-Compatible": "IE=Edge,chrome=1",
	  "Strict-Transport-Security": "max-age=31536000; preload",
	  "Server": "nginx",
	  "X-Rid": "29b6ee67221ff98e13407aa47ae6e40b",
	  "Connection": "close",
	  "Vary": "Accept-Encoding",
	  "P3p": "CP='Tumblr's privacy policy is available here: https://www.tumblr.com/policy/en/privacy'",
	  "Content-Length": "2353",
	  "Date": "Tue, 23 Nov 2021 00:04:14 GMT",
	  "Content-Type": "application/json; charset=utf-8"
	}

**Comment by sorin-costea** [comment]
Attached the response (slightly edited) and response headers.

**Comment by cyle** [comment]
Sorry about that -- the follow route will now return a `429 Limit Exceeded` when you've hit your follow limit for the day! And `followed` will be `false` if the requesting user could not follow the blog for some reason.
