### ISSUE TITLE
Issue hitting the `/likes` endpoint

### ISSUE THREAD

**Issue by juancoob** [tumblr/docs#67]
Hello Tumblr team! :wave: I think I found an issue hitting [the `/likes` endpoint](https://www.tumblr.com/docs/en/api/v2#likes--retrieve-blogs-likes)

## What is the issue? :thinking: 

The `limit` parameter is not working correctly. The likes number **(n)** is always lower than the expected result. I mean, the endpoint always retrieves an extra result **(n + 1)**

## What do we get? :mag_right:

Using the endpoint without the limit defined `api.tumblr.com/v2/blog/{blog-identifier}/likes?api_key={key}`, we get 21 results by default instead of 20: [likes.json.zip](https://github.com/tumblr/docs/files/7628338/likes.json.zip)
In case we define a limit **(n)**, we always get **(n + 1)**. Fortunately, if we add another parameter like `before`, it will work as it should be.

## What should we get? :wrench:

We should get the default/defined likes number independently of the parameters used to avoid confusion.

Thanks!

**Comment by cyle** [comment]
Hey @juancoob , thanks for the report! I can reproduce this issue, too. We'll fix this up, and we'll let you know here when it's resolved.
