### ISSUE TITLE
API/apps behaviour inconsistent (when blocked?)

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#69]
I try to /follow this blog - I receive a perfect looking 200 OK answer, but with followed=false.

But there's more to it:
- from the web dashboard, if I search to it, it won't show it in results (only "go to @ blogname")
- from that result, if I go to it, it shows "meditate for a while on this empty..."
- however, if I go directly to its address from the same browser (so same logged in session) I can see its posts - just without buttons to interact
- from the android app dash, again no direct result, only go to @
- if I go to it, it loads the blog header and avatar (so all buttons are there) but without posts (just the waiting wheel rotating forever)

I assume that I'm blocked, but in that case I shouldn't be able to see it at all, right? And the API should give a 404 or something... Like this, it's just a mixup so I don't even know what to believe. Unless the mixup is by design :))

**Comment by cyle** [comment]
I can't confirm whether or not you're blocked (obviously, not enough info here), but in general, the experience of looking at a blog which has blocked you can be "weird" in these ways, potentially. There could also be something wrong with the blog, or it may be terminated/suspended/deactivated/in an odd state. If it's a specific blog you want help with, I'd suggest [reaching out to Support](https://www.tumblr.com/support).

**Comment by sorin-costea** [comment]
Oh well, then I'll just assume "blocked" and leave it at that. Thank you! :)
