### ISSUE TITLE
Keep getting 404 or 401 errors on `/v2/user/like` endpoint

### ISSUE THREAD

**Issue by Saw-mon-and-Natalie** [tumblr/docs#7]
When sending a `POST` request to the [`/v2/user/like`](https://www.tumblr.com/docs/en/api/v2#userlike--like-a-post), I get a `404` or `401` error for some posts. I tried with `pytumblr` and Postman. 

Upon further troubleshooting, I noticed even on `tumblr` using one of my accounts I can't like those specific posts and I get `403` error on `https://www.tumblr.com/svc/like`.  On one of those specific posts, I noticed the post timestamp is in the future relative to my local time.

This seems to be similar to  #6 issue. But I also tried passing the request parameters as `JSON` and I would still get the same errors.

Any help would be appreciated.

**Comment by Saw-mon-and-Natalie** [comment]
looks like I might have hit `1000 likes/day`.
Are the tumblr daily/hourly limits officially documented anywhere?

**Comment by cyle** [comment]
hey @Saw-mon-and-Natalie, a few things, hope this helps:

- We do have rate limits, so if you receive a `429 Limit Exceeded` HTTP response, that means you've reached one! I'll see if I can make the documentation clearer about this.
- There are many reasons why you might get a `403 Forbidden`, but regardless of the reason, it means you cannot do the action you are trying to perform and you should not try again.
- `401 Unauthorized` usually means either the token you provided is invalid, or as I mentioned in #6, there could be an issue with the way you're calculating the OAuth1 signature in your request.

Overall Tumblr's API follows the standard conventions with its HTTP response codes. A `404 Not Found` means the resource wasn't found for some reason, a `403 Forbidden` means you're not allowed to do the thing you're trying to do, a `400 Bad Request` means there's something invalid in the request itself, a `401 Unauthorized` means there's something wrong with your authorization token, etc etc.

**Comment by Saw-mon-and-Natalie** [comment]
Hey @cyle ,

- Thank you. I wasn't getting `429` errors and I was checking for `X-Ratelimit-...` headers. I know there are hourly and daily limits for the API endpoints. But I wasn't hitting those limits.
- The `401, 404` errors were produced interchangeably using the API endpoints.
- The `403` error was generated by just using tumblr like a normal user through `chrome` browser.

It seemed all these errors were generated because of the `1000 likes per day per user`. 
But I can't find any official documentation that states this limit. I found the `1000 likes` limit through some posts by tumblr users.

**Comment by cyle** [comment]
@Saw-mon-and-Natalie Unfortunately I can't help diagnose this further without more details, and the Github issues page isn't the best way to report problems unless it's something specific about our documentation -- if you'd like, please file a support ticket over at https://www.tumblr.com/support and we'll see if we can help your specific case.

**Comment by cyle** [comment]
Hello @Saw-mon-and-Natalie , I've updated the public documentation with our rate limits here https://github.com/tumblr/docs/blob/master/api.md#rate-limits -- hope this helps!

**Comment by Saw-mon-and-Natalie** [comment]
Hi @cyle, thank you so much. These numbers are going to be really useful.

A few questions:

- Are the `per hour/day` sliding windows or setup using `tumblr` server clocks?
- Are there also limits for `posts/likes/...` per max life of a `user/blog`? I read somewhere that a user can like around `99,999` posts during its lifetime and once it reaches that cap it cannot like more posts.

**Comment by cyle** [comment]
> Are the `per hour/day` sliding windows or setup using `tumblr` server clocks?

These limits should be per calendar day according to Tumblr's server clocks.

> Are there also limits for `posts/likes/...` per max life of a user/blog?

There's actually only one "lifetime" limit related to the rate limits I've included in the docs, and that's the total number of blogs you can follow, which is currently capped at 5,000. I'll see if I can add this to the doc for clarity -- thanks for asking!

**Comment by cyle** [comment]
Hey @Saw-mon-and-Natalie sorry for taking so long on this but I've added a few of these "lifetime" limits here in the latest commit https://github.com/tumblr/docs/commit/1f6706f14f440cd77bacbbbc94acc4749bbf3d24#diff-00e71df22262087fd8ad820708997657R148-R155

I'll close this issue. Thanks for writing in!

**Comment by Saw-mon-and-Natalie** [comment]
Thanks, @cyle .
