### ISSUE TITLE
OAuth2 authorization endpoint requires redirect URI, but the parameter is not documented

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#70]
When multiple URIs are defined, you're required to pass the redirect URI you wish to use to the authorization endpoint. Otherwise, you get an `A redirect URI must be supplied when multiple redirect URIs are registered` error. However, the authorization endpoint is not documented as taking a `redirect_uri` parameter. Instead, the docs say only "Tumblr will redirect them to the OAuth2 redirect URL that you set when creating your application."

**Comment by cyle** [comment]
Good catch, we're working to fix up the docs for this, thanks! 👍

**Comment by cyle** [comment]
Docs updated!
