### ISSUE TITLE
How to make an OAuth signed POST request to api.tumblr.com/v2/blog/{blog-identifier}/posts (Python)

### ISSUE THREAD

**Issue by katurian** [tumblr/docs#72]
Hey, Tumblr!

So I have my Tumblr application's client key, client secret, resource owner key, and resource owner secret. I used these tokens to create an OAuth signature using the [Requests-OAuthlib](https://requests-oauthlib.readthedocs.io/en/latest/oauth1_workflow.html) Python library. Like this:

`headeroauth = OAuth1(client_key, client_secret, resource_owner_key, resource_owner_secret, signature_type='auth_header')`

I added this signature to the `auth` parameter of my POST request:, as you can see here

`r = requests.post(f'https://api.tumblr.com/v2/blog/{user}/posts', json={'parent_tumblelog_uuid': uuid, 'parent_post_id': post_id, 'reblog_key': reblog_key, 'date': iso}, auth=headeroauth, headers=headers, verify=False, allow_redirects=False)`

However, when I run my code, I receive this error from the Tumblr API:

`{'meta': {'status': 401, 'msg': 'Unauthorized'}, 'response': [], 'errors': [{'title': 'Unauthorized', 'code': 1016, 'detail': 'Unable to authorize'}]}`

I know my credentials are correct, so what is happening and how can I fix it?

**Comment by sndsgd** [comment]
@katurian It sounds like you may be excluding some parameters from the base string that the signature is derived from. For example, you need to include the http request method, and the encoded uri as parameters in the signature. You can find more details here: https://datatracker.ietf.org/doc/html/rfc5849#section-3.4.1.1.

You may be interested in using OAuth2, which would allow you skip the signature generation altogether: https://www.tumblr.com/docs/en/api/v2#oauth2-authorization.

**Comment by cyle** [comment]
Hello! I'd strongly suggest leveraging OAuth2 as @sndsgd points out above, but also:

> I added this signature to the auth parameter of my POST request:, as you can see here

OAuth1 authorization should be sent to the Tumblr API via the `Authorization` request header, not a body parameter. That's probably one potential problem here.

**Comment by katurian** [comment]
Okay, thanks. I am trying OAuth2 now. Just wondering, how are these request parameters passed:

![image](https://user-images.githubusercontent.com/35544223/151656867-e9a96989-04f4-4863-aac1-dc82522c910d.png)

Through the headers or the request body?

**Comment by sanmai** [comment]
Yes, this has to be a [POST request with `application/x-www-form-urlencoded` content type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST). With [httpie](https://httpie.io/) it goes like this:
```
http --form POST https://api.tumblr.com/v2/oauth2/token grant_type=authorization_code code={code} client_id={consumer_key} client_secret={consumer_secret}
```
And then you can use the access token like so:
```
http GET https://api.tumblr.com/v2/user/info 'Authorization: Bearer {access_token}'
```

**Comment by katurian** [comment]
Hey Alexey, thanks for the help.

I was able to get the OAuth2 access token by using that first HTTPie command. Your GET request also worked perfectly, but when I try to send a POST request instead I receive this error from Tumblr's API:

```
{
    "errors": [
        {
            "code": 1035,
            "detail": "Unable to authorize",
            "title": "Unauthorized"
        }
    ],
    "meta": {
        "msg": "Unauthorized",
        "status": 401
    },
    "response": []
}
```

My HTTPie command: 

```
http --form POST https://api.tumblr.com/v2/blog/transpanation.tumblr.com/posts content=[content] "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

I believe the issue is I am only giving the application read access instead of read and write access during the OAuth handling process:

![image](https://user-images.githubusercontent.com/35544223/152263695-01720bfc-6fb0-4c9e-b5c7-22955f24833d.png)

How do I give my app Read and Write privs using OAuth2 instead of Oauth1? Thanks.

Kate

**Comment by sanmai** [comment]
You'll need to add `scope=write` to your initial request:
```
https://www.tumblr.com/oauth2/authorize?client_id=...&response_type=code&scope=write&...
```
You might also make use of `offline_access`.

**Comment by katurian** [comment]
Yes! That worked, thank you so much Alexey. I will close the thread now. By the way, if anyone else is struggling to complete OAuth2 exchange here's what I did in Python:

https://gist.github.com/knmkr/e2c8578f833d86da3b567299525f6735

I edited this person's flask app to work with Tumblr's OAuth2 flow instead of Github's. Then, I hosted the flask script at https://replit.com. The public URL will be something like `https://yourapp.yourusername.repl.co`. Set your Tumblr application's OAuth2 redirect URL to `https://yourapp.yourusername.repl.co/callback` (you can change your application's fields at https://www.tumblr.com/oauth/apps). After that, just navigate back to `https://yourapp.yourusername.repl.co` and it will redirect you to [Tumblr's OAuth2 authorization endpoint](https://www.tumblr.com/docs/en/api/v2#oauth2authorize---authorization-request). Once you give the application read and write permissions, Tumblr will redirect you _again_ to `https://yourapp.yourusername.repl.co/callback`. Now you should see a URL with your authorization token in the address bar. This is what you use to get your OAuth2 bearer token from Tumblr's API!
