### ISSUE TITLE
/unfollow endpoint wrong answer when blog is password-protected

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#75]
(I assume it's a password-protected blog because when looking at https://username.tumblr.com I get redirected to https://www.tumblr.com/blog_auth/username and presented with a white page with a captcha and a password field)

Anyway, when trying to unfollow this blog via the API, the /user/unfollow API returns 200 OK with this body:

{"meta":{"status":200,"msg":"OK"},"response":{"blog":false}}

Which of course cannot be parsed - the "blog" should be a blog object... or if not, should be null or empty or whatever - not a boolean. Or is /unfollow not supposed anymore to return the blog object?

**Comment by cyle** [comment]
> Which of course cannot be parsed - the "blog" should be a blog object... or if not, should be null or empty or whatever - not a boolean. Or is /unfollow not supposed anymore to return the blog object?

I can get to [that blog just fine](https://username.tumblr.com/), but it looks like you may have found a bug -- we should be returning an empty object in that case. We'll get this fixed up! Thank you for reporting it.

**Comment by sorin-costea** [comment]
Haha no it wasn't "username" I just didn't want to publish somebody else's blog :) Thank you!
