### ISSUE TITLE
Is there a way to check remaining per-day actions?

### ISSUE THREAD

**Issue by AprilSylph** [tumblr/docs#79]
https://github.com/tumblr/docs/blob/master/api.md#rate-limits
> - 250 new posts (including reblogs) per day, per user.
> - 150 images uploaded per day, per user.
> - 200 follows per day, per user.
> - 1,000 likes per day, per user.
> - 10 new blogs per day, per user.
> - 20 videos uploaded per day, per user.
> - 60 minutes of total video uploaded per day, per user.

Is there any way for an account to access its current counts for these?

In particular, a significant number of people seem to want to know how far they are from post limit each day. There are tools (such as https://postlimit.com/) designed to create a guess, but doing so takes many API calls to fetch all posts in the current calendar day. Factoring in sideblogs only increases this work.

In the meantime, or if there are reasons I've not thought of for these counts to be obfuscated, it would be nice to get additional information on this paragraph:
> Note that these rate limits are based on the Tumblr servers' internal clocks and that the daily limits are per calendar day.

- What UTC offset do Tumblr's servers use?
- Does this change to account for DST, or is it constant?

**Comment by sndsgd** [comment]
Thanks for creating this issue @AprilSylph. We're going to add a new route to expose user limits/status, and we'll address your other questions in a documentation update.

**Comment by sndsgd** [comment]
@AprilSylph the new route is live: https://github.com/tumblr/docs/blob/master/api.md#userlimits--get-a-users-limits.

Each limit object includes a `reset_at` timestamp that I believe should resolve questions about timezone/DST while eliminating requirements for future docs updates should we make any time related changes internally.

Going to close this out for now. If you'd like to see further changes, please let us know!
