### ISSUE TITLE
Media array makes it hard to pick the correct source for rendering

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#8]
## Problem:

Generally, a media array can contain sources that have been

1. resized
2. transcoded
3. or cropped

from the original authored media. However, because the only properties on source are `type`, `width`, and `height`, it's hard to programmatically determine which sources are valid for rendering and which ones should be excluded.

For a simplified example, if I have an array of 2 sources: [250, 100] and [250, 250], which one do I use to render the image? Now, I know by observation that the 250x250 is probably tumblr's square crop derivation. However, that's not a contract that's guaranteed by the API, and it's difficult, cumbersome, and error-prone to hard-code hacks like this into my rendering code. (and what if someone actually uploads an image that's 250x250?)

Right now this information is *kind* of contained in the image URL, but that has a lot of the same downsides—there are two different URL formats, they may change at any moment, etc.

We should have some authoritative and canonical way of figuring out which media sources are safe to render in what situations.

## Proposal:

Add a property that specifies the list of transforms/derivations applied to the media source. Original images would have an empty array, images that were only resized (preserving aspect ratio) would have `['resized']`, and 75sq derivations would have `['resized', 'cropped']`. API clients can then pick and choose which sources are appropriate for a given situation. Non-cropped sources, for example. Or for a different example, in a full-size viewer, you would only use transcoded media, and exclude resized media.

### Alternatives

Alternatively, indicate that some source in a source array is the canonical, original media object, (maybe the first one?) and require clients to figure out what derivations apply themselves. This is less work for the server, but it makes the API client logic more complicated—they need to, e.g. figure out the original aspect ratio, exclude sources that are outside of some epsilon of tolerance (since the aspect ratios of pixel-rounded images are never going to be precisely equal), handle duplicate sources (for the 250x250 case), etc.

**Comment by nightpool** [comment]
Right now I'm blacklisting sources based on their URLs. I'm interested to hear how the in-house tumblr api clients are handling this issue.

**Comment by nightpool** [comment]
so I think the key thing here is:

> Long story short: these expected image widths are hardcoded on the client and server.

Which is the main thing for me—looking at this list of images, i have no idea which ones are cropped/somehow destructively transformed and which ones aren't. If the list of returned sizes is guaranteed as part of the API contract, then adding that into the docs and letting apps make decisions based on it seems like the right way forward. It does sound a lot more confusing then a cropped indicator though—I would prefer something that didn't require me to be reliant on specific lists of hardcoded sizes.

> In this case, you'd get a 250x250 version of the image, and all of the smaller size classes, never the bigger ones

right, i'm saying "if we hardcode a list of size classes, what does the client do when someone uploads a 250x250 image"? If the list of size classes was 250sq, 150, and 100sq, would it "skip" the 250sq in favor of the 150px wide size, even though the 250sq would actually be the correct image to show?

> "Resized" is a little tough for me to think through on my side because technically all images you get via Tumblr are resized and/or transcoded in some way

Yep, i get that, just wanted to convey the idea that this is a technique that can be applied regardless of the specific derivations involved, even if all of the media *does* end up having a `resized` feature, it's occasionally useful to apps to have that stated explicitly.

**Comment by cyle** [comment]
> looking at this list of images, i have no idea which ones are cropped/somehow destructively transformed and which ones aren't. If the list of returned sizes is guaranteed as part of the API contract, then adding that into the docs and letting apps make decisions based on it seems like the right way forward.

> just wanted to convey the idea that this is a technique that can be applied regardless of the specific derivations involved, even if all of the media does end up having a resized feature, it's occasionally useful to apps to have that stated explicitly.

Yep, make sense. I'm almost always in favor of making an API more explicit even if that means it has to be verbose. Generally the only time I'm not in favor of that is when it leads to values that will always be true or the same, which is usually the case in this instance, hence why we don't already have this info in the API response. But it makes total sense for a third party who isn't aware of that, as you've pointed out. I'm mainly hesitant to use the `'resized'` "tag" because it would _always_ be there.

> If the list of size classes was 250sq, 150, and 100sq, would it "skip" the 250sq in favor of the 150px wide size, even though the 250sq would actually be the correct image to show?

It depends, and I'd have to test myself to see what exactly happens where. We don't always provide all of the size classes for every request. We generally only pass along the square/cropped sizes for specific use cases when they're needed. In the case of a regular old image in a regular old post, it shouldn't skip the 250sq image size class if that class works for the given image.

**Comment by cyle** [comment]
To update and close this, I've updated NPF to return `cropped: true` in media objects when that media has been cropped, as well as `has_original_dimensions: true` in media objects when that media matches the dimensions of the original uploaded media. You can see this here: https://github.com/tumblr/docs/blob/master/npf-spec.md#media-objects

Hopefully this helps!

**Comment by nightpool** [comment]
that's great, thanks so much!
