### ISSUE TITLE
fetching post /notes always returns something

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#83]
Fetching post /notes with a bad "before_timestamp" (equal or before the post timestamp) returns always one note - the "posted" one. I would rather expect an empty notes array...

**Comment by cyle** [comment]
Thanks for calling this out! That is indeed a bug. We should be returning an empty when the given `before_timestamp` is before the post creation time. We'll get this fixed up. 👌

**Comment by cyle** [comment]
this should be fixed now!
