### ISSUE TITLE
/posts POST end point returns error when posting a video file via multipart/form-data

### ISSUE THREAD

**Issue by bennworks** [tumblr/docs#88]
The multipart form request is failing when creating a new post containing a video file.
The returned error is following.
```
{
    "meta": {"status": 400,"msg": "Bad Request"},
	"response": [],
	"errors": [{
		"title": "Bad Request",
		"code": 0,
		"detail": "Measly little error. Try again."
	},{same error},{same error},{same error}]
}

```
But detail is changing slightly whenever making a new request like this: 

```
{"title":"Bad Request","code":0,"detail":"Internet strangeness. Try again."}
{"title":"Bad Request","code":0,"detail":"Hit a glitch. Try again."}
{"title":"Bad Request","code":0,"detail":"Something broke. Try again."}
{"title":"Bad Request","code":0,"detail":"Something flubbed. Try again."}
{"title":"Bad Request","code":0,"detail":"Measly little error. Try again."}
{"title":"Bad Request","code":0,"detail":"Minor hiccup. Try again."}
```

My multipart form request is as following.

```
content-type	multipart/form-data; charset=utf-8; boundary=END_OF_PART
content-length	1058135

--END_OF_PART
Content-Disposition: form-data; name="json"
Content-Type: application/json; charset=utf-8

{
    "state": "draft",
    "content": [
        {
            "media": [
                {
                    "height": 1280,
                    "identifier": "randomstring",
                    "type": "video/mp4",
                    "width": 720
                }
            ],
            "type": "video"
        }
    ],
    "layout": [
        {
            "type": "rows",
            "display": [
                {
                    "blocks": [
                        0
                    ]
                }
            ]
        }
    ]
}
--END_OF_PART
Content-Disposition: form-data; name="randomstring"; filename="filename.MOV"
Content-Type: video/mp4

{file data}
--END_OF_PART--
```
PS. Additionally, when posting image files using the same method, it succeeds. The multipart form request is nearly the same content except Content-Type and file data.

**Comment by cyle** [comment]
Hey @bennworks -- we'll take a look at this and get back to you about this and #87, they're likely related. Thank you for all of the detail here!

**Comment by bennworks** [comment]
> Hey @bennworks -- we'll take a look at this and get back to you about this and #87, they're likely related. Thank you for all of the detail here!

It's been a month already. I wonder when it will be resolved.

**Comment by bennworks** [comment]
Hi @cyle  I'm still desperately waiting for this issue to be resolved. Also, please check if the cause of the problem is because "oauth 1" is used.

**Comment by sirreal** [comment]
I was able to get this working for `tumblr.js`, there's an integration test example with a video upload. The request we send looks a lot like the example you shared @bennworks. Were you able to get this working?

If you're using Node.js, you might try with a v4 release of tumblr.js (currently prerelease, but available on npm tagged `next`).

**Comment by bennworks** [comment]
Thank @sirreal for providing information. Unfortunately, I'm still stuck with this issue. I'm developing in mobile platform. So I can't use tumblr.js. BTW, do you use oAuth1 or oAuth2? I'm using oAuth1 and I'm wondering if the authentication method has anything to do with this issue.

**Comment by sanmai** [comment]
Error 400 probably means authentication method is not the problem.

**Comment by sirreal** [comment]
I've been using oauth1 to successfully create NPF posts.

@bennworks one idea is to capture a request made using tumblr.js to create a post, then compare that with your requests.

**Comment by bennworks** [comment]
@sirreal I've tested various video files such as exact video downloaded from Tumblr, small size etc. I have no problem in uploading multipart image data with the same module. And I have captured the upload data stream for various apps(mine and Tumblr one). Captured data shows no problem.

**Comment by bennworks** [comment]
@cyle , @sirreal  I found the cause of this bug finally. The media property of video content is not 'Array' type. It's a single entity with {} only. After removing [](array), video upload works normally. I use same module for image/video, so I didn't notice until now. Thank you for your help so far.
