### ISSUE TITLE
subtype 'indented' expected rendering

### ISSUE THREAD

**Issue by nightpool** [tumblr/docs#9]
as far as I can tell, no official clients currently render subtype: indented. What is the authorship intent for subtype `indented`, and how is it different from `quote`? (which it seems to be being used in place of)

(i.e., as an author, when would I choose to use one over the other?)

**Comment by cyle** [comment]
Hey @nightpool , `indented` is still a work in progress on our end. It's been included in the doc for completeness, and we'll be rolling out official support for it soon. The intention behind it is to mirror the "blockquote" behavior on the current web editor. The existing `quote` text block subtype is meant for short quotes, while `intended` can be used for longer quotes. Some folks use the `indented` style on web to caption photos.

Seems like a good idea to include some kind of intentionality behind the different subtypes though, right now it's just a list. I'll see what I can do!

**Comment by nightpool** [comment]
thanks cyle! so this is basically forward-porting the distinction between
blockquote and quote posts? my understanding is that the standard quote
type rendering was supposed to change size to adapt to longer or shorter
texts—was this impractical?

**Comment by cyle** [comment]
> so this is basically forward-porting the distinction between blockquote and quote posts?

Kind of? I guess you could say it that way, even though there's never been a "blockquote" post, I think I get what you mean. The `quote` text block subtype was originally meant to cover _all_ kinds of quotes, long and short, but the actual quote post type rarely had long quotes. However, the `<blockquote>` tag used by the rich text editor on web usually had long quotes, and we used the same `quote` subtype for those when converting HTML to NPF. One of the actual changes we're making is that old `<blockquote>` usage in HTML will become `intended` subtype text blocks. Stay tuned to future app releases for more related changes. 😄 

> my understanding is that the standard quote type rendering was supposed to change size to adapt to longer or shorter texts—was this impractical?

Impractical for the use case of when folks make very long quotes, yeah, hence this change.

**Comment by nightpool** [comment]
okay, cool. one thing I also noticed that may be related is that HTML
blockquotes with multiple paragraphs, when converted to NPF, only have the
quote type applied to the first block, and subsequent blocks show up
without a subtype. is this on your radar?

**Comment by cyle** [comment]
>  is this on your radar?

Yes, it definitely is. 👌

**Comment by cyle** [comment]
I've updated the public NPF docs with some color around what these text block subtypes are intended for and how the official Tumblr clients use them here https://github.com/tumblr/docs/commit/1f6706f14f440cd77bacbbbc94acc4749bbf3d24#diff-7e7a5c27067716a728a6922accb77fecR251-R260

Closing this issue. Thanks!

**Comment by nightpool** [comment]
💜
