### ISSUE TITLE
Account terminated... 

### ISSUE THREAD

**Issue by sorin-costea** [tumblr/docs#90]
A couple of days ago my girl's blog was terminated. She was kicked out of the session then at login got greeted with the stern message "your account was terminated. You can contact support here". Or something along the lines. Well, support didn't come around answering all these days and she slipped into a reclusive episode, because in her major depression, she believed the blog was her only accomplishment in life. Yes, our hellsite was known for supporting those in trouble, those lonely, those misunderstood. Until now, at least. On the other hand I've been contacted in the last 24 hours by the regular amount of Tumblr hookers, here a few recent names if you like: lily1244, mistresstitiy, jgroo, sandra4405221, roselinesmith, tianee, goddess-sandra... should I go on? Go check them, they're all fine, spreading their porn and spam, against all the reports I ever did. But no, instead it had to be terminated an active account with 9k followers, posting daily for the last three years her original street pictures of Venice and reblogging classical art, flowers and cats. Is Tumblr going the way of Facebook, random automated moderation and zero humanity? The answers I got from other fellow tumblers tell me this was not a singular case, so looking from here and squinting a bit it seems like becoming a warmer home to hookers and crypto spam than to original creators - or to simple people trying to find a little bit of appreciation from strangers. Oh yes, I'm upset, upset for seeing her thrown out with the garbage, actually rather no, thrown out INSTEAD of the garbage. Congratulation, hellsite, for discovering a good way to turn the tongue-in-cheek nickname into cold reality. The only question is, how long will you continue on this road?

**Comment by cyle** [comment]
Hello @sorin-costea , I'm sorry to hear you're experiencing this issue, but unfortunately the docs repo is not the right venue for solving it. Please [contact Support](https://tumblr.com/support) (try again, if you'd like) for help with this. If the blog was wrongly terminated, we'll restore it. And thank you for reporting those blogs, we read every report and take action when we find policy violations.

**Comment by sorin-costea** [comment]
When I was reporting a wrong button color, support answered within two days. For an account termination it's already a week without reply. Priorities indeed. But I'll try more...

**Comment by sorin-costea** [comment]
@cyle  do you have a suggestion for whe the support doesn't bother to answer anything, for more than two weeks now? It's not the workload - I opened another trivial support case for some editor hiccup, and I had answers every second day.

**Comment by sorin-costea** [comment]
@cyle three weeks in, still no answer from support. Is ghosting the standard approach to account terminations? Are you the last human left there?

**Comment by sanmai** [comment]
As @cyle said, docs repo is not the right venue for solving this issue.
