### ISSUE TITLE
Documentation for reblog controls

### ISSUE THREAD

**Issue by madeleine-b** [tumblr/docs#91]
I know [reblog controls](https://staff.tumblr.com/post/685964115655737344/introducing-reblog-controls) are still rolling out to everyone but I don't seem to see info about it in the docs. Has it been added to the third-party API yet?

**Comment by cyle** [comment]
hey @madeleine-b , it has now! check out `interactability_reblog` via https://github.com/tumblr/docs/commit/96e9172556c31e2488aaff0844476ba62b706527
