### ISSUE TITLE
NPF Spec: Outdated maximum image count

### ISSUE THREAD

**Issue by marcustyphoon** [tumblr/docs#94]
https://github.com/tumblr/docs/blob/930050b56811a35ca75e71c7cb2330002ddc0573/npf-spec.md?plain=1#L1905-L1907

As of [this Changes post](https://www.tumblr.com/changes/691125579026743296/friday-july-29th-2022), this is no longer true:

> We’ve bumped the image limit in the beta post editor on web from 10 to 30. The post editor in the apps still has the 10 image limit due to some technical limitations we’re working on (you can still edit a post with 10+ images in the app, you just can’t add any more).

**Comment by sanmai** [comment]
Thanks for calling this out! We'll get this fixed up. 👌

**Comment by rtio** [comment]
We have [updated the specs](https://github.tumblr.net/Tumblr/tumblr-public-docs/pull/71#issuecomment-596704), thanks for that. I'll close this issue.

**Comment by cyle** [comment]
sure thing, thanks!
